//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstractTransactionResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractTransactionResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractResponse">
 *       &lt;sequence>
 *         &lt;element name="TRNUID" type="{http://ofx.net/types/2003/04}GloballyUniqueUserIdType"/>
 *         &lt;element name="STATUS" type="{http://ofx.net/types/2003/04}Status"/>
 *         &lt;element name="CLTCOOKIE" type="{http://ofx.net/types/2003/04}IdType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractTransactionResponse", propOrder = {
    "trnuid",
    "status",
    "cltcookie"
})
@XmlSeeAlso({
    BillTableStructureTransactionResponse.class,
    PayeeTransactionResponse.class,
    CreditCardStatementEndTransactionResponse.class,
    StatementTransactionResponse.class,
    StatementEndTransactionResponse.class,
    PresentmentMailTransactionResponse.class,
    InterTransactionResponse.class,
    FindBillerTransactionResponse.class,
    InvestmentStatementTransactionResponse.class,
    CreditCardStatementTransactionResponse.class,
    AccountInfoTransactionResponse.class,
    SecurityListTransactionResponse.class,
    StopCheckTransactionResponse.class,
    RecurringIntraTransactionResponse.class,
    AccountTransactionResponse.class,
    BankMailTransactionResponse.class,
    PresentmentGroupAccountInfoTransactionResponse.class,
    PaymentTransactionResponse.class,
    MFAChallengeTransactionResponse.class,
    IntraTransactionResponse.class,
    PresentmentNotifyTransactionResponse.class,
    PresentmentListTransactionResponse.class,
    BillStatusModTransactionResponse.class,
    EnrollTransactionResponse.class,
    ChangeUserInfoTransactionResponse.class,
    PaymentInquiryTransactionResponse.class,
    PaymentMailTransactionResponse.class,
    InvestmentMailTransactionResponse.class,
    RecurringPaymentTransactionResponse.class,
    PresentmentDetailTransactionResponse.class,
    WireTransactionResponse.class,
    MailTransactionResponse.class,
    ChallengeTransactionResponse.class,
    RecurringInterTransactionResponse.class,
    ProfileTransactionResponse.class,
    GetMimeTransactionResponse.class,
    PinChangeTransactionResponse.class
})
public abstract class AbstractTransactionResponse
    extends AbstractResponse
{

    @XmlElement(name = "TRNUID", required = true)
    protected String trnuid;
    @XmlElement(name = "STATUS", required = true)
    protected Status status;
    @XmlElement(name = "CLTCOOKIE")
    protected String cltcookie;

    /**
     * Gets the value of the trnuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRNUID() {
        return trnuid;
    }

    /**
     * Sets the value of the trnuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRNUID(String value) {
        this.trnuid = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getSTATUS() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setSTATUS(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the cltcookie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLTCOOKIE() {
        return cltcookie;
    }

    /**
     * Sets the value of the cltcookie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLTCOOKIE(String value) {
        this.cltcookie = value;
    }

}
