//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AbstractTaxW2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractTaxW2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TAXYEAR" type="{http://ofx.net/types/2003/04}YearType"/>
 *         &lt;element name="CNTRLNO" type="{http://ofx.net/types/2003/04}ControlNumber" minOccurs="0"/>
 *         &lt;element name="VOID" type="{http://ofx.net/types/2003/04}BooleanType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractTaxW2", propOrder = {
    "taxyear",
    "cntrlno",
    "_void"
})
@XmlSeeAlso({
    TaxW2V100 .class,
    TaxW2V200 .class
})
public abstract class AbstractTaxW2 {

    @XmlElement(name = "TAXYEAR", required = true)
    protected XMLGregorianCalendar taxyear;
    @XmlElement(name = "CNTRLNO")
    protected String cntrlno;
    @XmlElement(name = "VOID")
    protected BooleanType _void;

    /**
     * Gets the value of the taxyear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTAXYEAR() {
        return taxyear;
    }

    /**
     * Sets the value of the taxyear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTAXYEAR(XMLGregorianCalendar value) {
        this.taxyear = value;
    }

    /**
     * Gets the value of the cntrlno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNTRLNO() {
        return cntrlno;
    }

    /**
     * Sets the value of the cntrlno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNTRLNO(String value) {
        this.cntrlno = value;
    }

    /**
     * Gets the value of the void property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getVOID() {
        return _void;
    }

    /**
     * Sets the value of the void property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setVOID(BooleanType value) {
        this._void = value;
    }

}
