//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstractSyncResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractSyncResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractResponse">
 *       &lt;sequence>
 *         &lt;element name="TOKEN" type="{http://ofx.net/types/2003/04}ServerIdType"/>
 *         &lt;element name="LOSTSYNC" type="{http://ofx.net/types/2003/04}BooleanType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractSyncResponse", propOrder = {
    "token",
    "lostsync"
})
@XmlSeeAlso({
    MailSyncResponse.class,
    InvestmentMailSyncResponse.class,
    BankMailSyncResponse.class,
    AccountSyncResponse.class,
    PaymentSyncResponse.class,
    RecurringIntraSyncResponse.class,
    WireSyncResponse.class,
    PaymentMailSyncResponse.class,
    RecurringPaymentSyncResponse.class,
    ChangeUserInfoSyncResponse.class,
    PayeeSyncResponse.class,
    RecurringInterSyncResponse.class,
    PresentmentMailSyncResponse.class,
    IntraSyncResponse.class,
    InterSyncResponse.class,
    StopCheckSyncResponse.class
})
public abstract class AbstractSyncResponse
    extends AbstractResponse
{

    @XmlElement(name = "TOKEN", required = true)
    protected String token;
    @XmlElement(name = "LOSTSYNC")
    protected BooleanType lostsync;

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOKEN() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOKEN(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the lostsync property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getLOSTSYNC() {
        return lostsync;
    }

    /**
     * Sets the value of the lostsync property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setLOSTSYNC(BooleanType value) {
        this.lostsync = value;
    }

}
