//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "ACCTINFORS" is of type "AccountInfoResponse"
 *       
 * 
 * <p>Java class for AccountInfoResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountInfoResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DTACCTUP" type="{http://ofx.net/types/2003/04}DateTimeType"/>
 *         &lt;element name="ACCTINFO" type="{http://ofx.net/types/2003/04}AccountInfo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountInfoResponse", propOrder = {
    "dtacctup",
    "acctinfo"
})
public class AccountInfoResponse {

    @XmlElement(name = "DTACCTUP", required = true)
    protected String dtacctup;
    @XmlElement(name = "ACCTINFO")
    protected List<AccountInfo> acctinfo;

    /**
     * Gets the value of the dtacctup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTACCTUP() {
        return dtacctup;
    }

    /**
     * Sets the value of the dtacctup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTACCTUP(String value) {
        this.dtacctup = value;
    }

    /**
     * Gets the value of the acctinfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acctinfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getACCTINFO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccountInfo }
     * 
     * 
     */
    public List<AccountInfo> getACCTINFO() {
        if (acctinfo == null) {
            acctinfo = new ArrayList<AccountInfo>();
        }
        return this.acctinfo;
    }

}
