//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "ADDLSTTAXWHAGG" is of type "AdditionalStateTaxWithheldAggregate"
 *       
 * 
 * <p>Java class for AdditionalStateTaxWithheldAggregate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdditionalStateTaxWithheldAggregate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="STTAXWH" type="{http://ofx.net/types/2003/04}AmountType"/>
 *         &lt;element name="PAYERSTATE" type="{http://ofx.net/types/2003/04}StateCodeType"/>
 *         &lt;element name="PAYERSTID" type="{http://ofx.net/types/2003/04}IdType" minOccurs="0"/>
 *         &lt;element name="STINCOME" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdditionalStateTaxWithheldAggregate", propOrder = {
    "sttaxwh",
    "payerstate",
    "payerstid",
    "stincome"
})
public class AdditionalStateTaxWithheldAggregate {

    @XmlElement(name = "STTAXWH", required = true)
    protected String sttaxwh;
    @XmlElement(name = "PAYERSTATE", required = true)
    protected String payerstate;
    @XmlElement(name = "PAYERSTID")
    protected String payerstid;
    @XmlElement(name = "STINCOME")
    protected String stincome;

    /**
     * Gets the value of the sttaxwh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTTAXWH() {
        return sttaxwh;
    }

    /**
     * Sets the value of the sttaxwh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTTAXWH(String value) {
        this.sttaxwh = value;
    }

    /**
     * Gets the value of the payerstate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYERSTATE() {
        return payerstate;
    }

    /**
     * Sets the value of the payerstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYERSTATE(String value) {
        this.payerstate = value;
    }

    /**
     * Gets the value of the payerstid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYERSTID() {
        return payerstid;
    }

    /**
     * Sets the value of the payerstid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYERSTID(String value) {
        this.payerstid = value;
    }

    /**
     * Gets the value of the stincome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTINCOME() {
        return stincome;
    }

    /**
     * Sets the value of the stincome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTINCOME(String value) {
        this.stincome = value;
    }

}
