//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "BANKMSGSET" is of type "BankMessageSet"
 *       
 * 
 * <p>Java class for BankMessageSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BankMessageSet">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractMessageSet">
 *       &lt;sequence>
 *         &lt;element name="BANKMSGSETV1" type="{http://ofx.net/types/2003/04}BankMessageSetV1"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BankMessageSet", propOrder = {
    "bankmsgsetv1"
})
public class BankMessageSet
    extends AbstractMessageSet
{

    @XmlElement(name = "BANKMSGSETV1", required = true)
    protected BankMessageSetV1 bankmsgsetv1;

    /**
     * Gets the value of the bankmsgsetv1 property.
     * 
     * @return
     *     possible object is
     *     {@link BankMessageSetV1 }
     *     
     */
    public BankMessageSetV1 getBANKMSGSETV1() {
        return bankmsgsetv1;
    }

    /**
     * Sets the value of the bankmsgsetv1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankMessageSetV1 }
     *     
     */
    public void setBANKMSGSETV1(BankMessageSetV1 value) {
        this.bankmsgsetv1 = value;
    }

}
