//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 	      The OFX element "BILLDETAILROW" is of type "BillDetailRow"
 * 	    
 * 
 * <p>Java class for BillDetailRow complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillDetailRow">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="C" type="{http://ofx.net/types/2003/04}MessageType"/>
 *         &lt;element name="N" type="{http://ofx.net/types/2003/04}CharType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillDetailRow", propOrder = {
    "cOrN"
})
public class BillDetailRow {

    @XmlElementRefs({
        @XmlElementRef(name = "N", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "C", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<String>> cOrN;

    /**
     * Gets the value of the cOrN property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cOrN property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCOrN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getCOrN() {
        if (cOrN == null) {
            cOrN = new ArrayList<JAXBElement<String>>();
        }
        return this.cOrN;
    }

}
