//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "BILLPAYMSGSRSV1" is of type "BillPayResponseMessageSetV1"
 *       
 * 
 * <p>Java class for BillPayResponseMessageSetV1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillPayResponseMessageSetV1">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractResponseMessageSet">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="PAYEETRNRS" type="{http://ofx.net/types/2003/04}PayeeTransactionResponse"/>
 *           &lt;element name="PAYEESYNCRS" type="{http://ofx.net/types/2003/04}PayeeSyncResponse"/>
 *         &lt;/choice>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="PMTTRNRS" type="{http://ofx.net/types/2003/04}PaymentTransactionResponse"/>
 *           &lt;element name="RECPMTTRNRS" type="{http://ofx.net/types/2003/04}RecurringPaymentTransactionResponse"/>
 *           &lt;element name="PMTINQTRNRS" type="{http://ofx.net/types/2003/04}PaymentInquiryTransactionResponse"/>
 *           &lt;element name="PMTMAILTRNRS" type="{http://ofx.net/types/2003/04}PaymentMailTransactionResponse"/>
 *           &lt;element name="PMTSYNCRS" type="{http://ofx.net/types/2003/04}PaymentSyncResponse"/>
 *           &lt;element name="RECPMTSYNCRS" type="{http://ofx.net/types/2003/04}RecurringPaymentSyncResponse"/>
 *           &lt;element name="PMTMAILSYNCRS" type="{http://ofx.net/types/2003/04}PaymentMailSyncResponse"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillPayResponseMessageSetV1", propOrder = {
    "payeetrnrsOrPAYEESYNCRS",
    "pmttrnrsOrRECPMTTRNRSOrPMTINQTRNRS"
})
public class BillPayResponseMessageSetV1
    extends AbstractResponseMessageSet
{

    @XmlElements({
        @XmlElement(name = "PAYEETRNRS", type = PayeeTransactionResponse.class),
        @XmlElement(name = "PAYEESYNCRS", type = PayeeSyncResponse.class)
    })
    protected List<AbstractResponse> payeetrnrsOrPAYEESYNCRS;
    @XmlElements({
        @XmlElement(name = "PMTTRNRS", type = PaymentTransactionResponse.class),
        @XmlElement(name = "RECPMTTRNRS", type = RecurringPaymentTransactionResponse.class),
        @XmlElement(name = "PMTINQTRNRS", type = PaymentInquiryTransactionResponse.class),
        @XmlElement(name = "PMTMAILTRNRS", type = PaymentMailTransactionResponse.class),
        @XmlElement(name = "PMTSYNCRS", type = PaymentSyncResponse.class),
        @XmlElement(name = "RECPMTSYNCRS", type = RecurringPaymentSyncResponse.class),
        @XmlElement(name = "PMTMAILSYNCRS", type = PaymentMailSyncResponse.class)
    })
    protected List<AbstractResponse> pmttrnrsOrRECPMTTRNRSOrPMTINQTRNRS;

    /**
     * Gets the value of the payeetrnrsOrPAYEESYNCRS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payeetrnrsOrPAYEESYNCRS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPAYEETRNRSOrPAYEESYNCRS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PayeeTransactionResponse }
     * {@link PayeeSyncResponse }
     * 
     * 
     */
    public List<AbstractResponse> getPAYEETRNRSOrPAYEESYNCRS() {
        if (payeetrnrsOrPAYEESYNCRS == null) {
            payeetrnrsOrPAYEESYNCRS = new ArrayList<AbstractResponse>();
        }
        return this.payeetrnrsOrPAYEESYNCRS;
    }

    /**
     * Gets the value of the pmttrnrsOrRECPMTTRNRSOrPMTINQTRNRS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pmttrnrsOrRECPMTTRNRSOrPMTINQTRNRS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPMTTRNRSOrRECPMTTRNRSOrPMTINQTRNRS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentTransactionResponse }
     * {@link RecurringPaymentTransactionResponse }
     * {@link PaymentInquiryTransactionResponse }
     * {@link PaymentMailTransactionResponse }
     * {@link PaymentSyncResponse }
     * {@link RecurringPaymentSyncResponse }
     * {@link PaymentMailSyncResponse }
     * 
     * 
     */
    public List<AbstractResponse> getPMTTRNRSOrRECPMTTRNRSOrPMTINQTRNRS() {
        if (pmttrnrsOrRECPMTTRNRSOrPMTINQTRNRS == null) {
            pmttrnrsOrRECPMTTRNRSOrPMTINQTRNRS = new ArrayList<AbstractResponse>();
        }
        return this.pmttrnrsOrRECPMTTRNRSOrPMTINQTRNRS;
    }

}
