//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 	      The OFX element "BILLPMTSTATUS" is of type "BillPaymentstatus"
 * 	    
 * 
 * <p>Java class for BillPaymentstatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillPaymentstatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SRVRTID" type="{http://ofx.net/types/2003/04}ServerIdType" minOccurs="0"/>
 *         &lt;element name="BILLPMTSTATUSCODE" type="{http://ofx.net/types/2003/04}BillPaymentstatusCodeEnum"/>
 *         &lt;element name="DTEFF" type="{http://ofx.net/types/2003/04}DateTimeType"/>
 *         &lt;element name="STATUSMODBY" type="{http://ofx.net/types/2003/04}StatusModBYEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillPaymentstatus", propOrder = {
    "srvrtid",
    "billpmtstatuscode",
    "dteff",
    "statusmodby"
})
public class BillPaymentstatus {

    @XmlElement(name = "SRVRTID")
    protected String srvrtid;
    @XmlElement(name = "BILLPMTSTATUSCODE", required = true)
    protected BillPaymentstatusCodeEnum billpmtstatuscode;
    @XmlElement(name = "DTEFF", required = true)
    protected String dteff;
    @XmlElement(name = "STATUSMODBY")
    protected StatusModBYEnum statusmodby;

    /**
     * Gets the value of the srvrtid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSRVRTID() {
        return srvrtid;
    }

    /**
     * Sets the value of the srvrtid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSRVRTID(String value) {
        this.srvrtid = value;
    }

    /**
     * Gets the value of the billpmtstatuscode property.
     * 
     * @return
     *     possible object is
     *     {@link BillPaymentstatusCodeEnum }
     *     
     */
    public BillPaymentstatusCodeEnum getBILLPMTSTATUSCODE() {
        return billpmtstatuscode;
    }

    /**
     * Sets the value of the billpmtstatuscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillPaymentstatusCodeEnum }
     *     
     */
    public void setBILLPMTSTATUSCODE(BillPaymentstatusCodeEnum value) {
        this.billpmtstatuscode = value;
    }

    /**
     * Gets the value of the dteff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTEFF() {
        return dteff;
    }

    /**
     * Sets the value of the dteff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTEFF(String value) {
        this.dteff = value;
    }

    /**
     * Gets the value of the statusmodby property.
     * 
     * @return
     *     possible object is
     *     {@link StatusModBYEnum }
     *     
     */
    public StatusModBYEnum getSTATUSMODBY() {
        return statusmodby;
    }

    /**
     * Sets the value of the statusmodby property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusModBYEnum }
     *     
     */
    public void setSTATUSMODBY(StatusModBYEnum value) {
        this.statusmodby = value;
    }

}
