//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "CHALLENGETRNRS" is of type "ChallengeTransactionResponse"
 *       
 * 
 * <p>Java class for ChallengeTransactionResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChallengeTransactionResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractTransactionResponse">
 *       &lt;sequence>
 *         &lt;element name="CHALLENGERS" type="{http://ofx.net/types/2003/04}ChallengeResponse" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChallengeTransactionResponse", propOrder = {
    "challengers"
})
public class ChallengeTransactionResponse
    extends AbstractTransactionResponse
{

    @XmlElement(name = "CHALLENGERS")
    protected ChallengeResponse challengers;

    /**
     * Gets the value of the challengers property.
     * 
     * @return
     *     possible object is
     *     {@link ChallengeResponse }
     *     
     */
    public ChallengeResponse getCHALLENGERS() {
        return challengers;
    }

    /**
     * Sets the value of the challengers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChallengeResponse }
     *     
     */
    public void setCHALLENGERS(ChallengeResponse value) {
        this.challengers = value;
    }

}
