//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 	      The OFX element "COLDEF" is of type "ColumnDefinition"
 * 	    
 * 
 * <p>Java class for ColumnDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ColumnDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="COLNAME" type="{http://ofx.net/types/2003/04}GenericNameType"/>
 *         &lt;element name="COLTYPE" type="{http://ofx.net/types/2003/04}ColumnType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ColumnDefinition", propOrder = {
    "colname",
    "coltype"
})
public class ColumnDefinition {

    @XmlElement(name = "COLNAME", required = true)
    protected String colname;
    @XmlElement(name = "COLTYPE", required = true)
    protected String coltype;

    /**
     * Gets the value of the colname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOLNAME() {
        return colname;
    }

    /**
     * Sets the value of the colname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOLNAME(String value) {
        this.colname = value;
    }

    /**
     * Gets the value of the coltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOLTYPE() {
        return coltype;
    }

    /**
     * Sets the value of the coltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOLTYPE(String value) {
        this.coltype = value;
    }

}
