//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "CCSTMTENDTRNRQ" is of type "CreditCardStatementEndTransactionRequest"
 *       
 * 
 * <p>Java class for CreditCardStatementEndTransactionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditCardStatementEndTransactionRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractTransactionRequest">
 *       &lt;sequence>
 *         &lt;element name="CCSTMTENDRQ" type="{http://ofx.net/types/2003/04}CreditCardStatementEndRequest"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditCardStatementEndTransactionRequest", propOrder = {
    "ccstmtendrq"
})
public class CreditCardStatementEndTransactionRequest
    extends AbstractTransactionRequest
{

    @XmlElement(name = "CCSTMTENDRQ", required = true)
    protected CreditCardStatementEndRequest ccstmtendrq;

    /**
     * Gets the value of the ccstmtendrq property.
     * 
     * @return
     *     possible object is
     *     {@link CreditCardStatementEndRequest }
     *     
     */
    public CreditCardStatementEndRequest getCCSTMTENDRQ() {
        return ccstmtendrq;
    }

    /**
     * Sets the value of the ccstmtendrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditCardStatementEndRequest }
     *     
     */
    public void setCCSTMTENDRQ(CreditCardStatementEndRequest value) {
        this.ccstmtendrq = value;
    }

}
