//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "CREDITCARDMSGSET" is of type "CreditcardMessageSet"
 *       
 * 
 * <p>Java class for CreditcardMessageSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditcardMessageSet">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractMessageSet">
 *       &lt;sequence>
 *         &lt;element name="CREDITCARDMSGSETV1" type="{http://ofx.net/types/2003/04}CreditcardMessageSetV1"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditcardMessageSet", propOrder = {
    "creditcardmsgsetv1"
})
public class CreditcardMessageSet
    extends AbstractMessageSet
{

    @XmlElement(name = "CREDITCARDMSGSETV1", required = true)
    protected CreditcardMessageSetV1 creditcardmsgsetv1;

    /**
     * Gets the value of the creditcardmsgsetv1 property.
     * 
     * @return
     *     possible object is
     *     {@link CreditcardMessageSetV1 }
     *     
     */
    public CreditcardMessageSetV1 getCREDITCARDMSGSETV1() {
        return creditcardmsgsetv1;
    }

    /**
     * Sets the value of the creditcardmsgsetv1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditcardMessageSetV1 }
     *     
     */
    public void setCREDITCARDMSGSETV1(CreditcardMessageSetV1 value) {
        this.creditcardmsgsetv1 = value;
    }

}
