//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "ENROLLTRNRQ" is of type "EnrollTransactionRequest"
 *       
 * 
 * <p>Java class for EnrollTransactionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnrollTransactionRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractTransactionRequest">
 *       &lt;sequence>
 *         &lt;element name="ENROLLRQ" type="{http://ofx.net/types/2003/04}EnrollRequest"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnrollTransactionRequest", propOrder = {
    "enrollrq"
})
public class EnrollTransactionRequest
    extends AbstractTransactionRequest
{

    @XmlElement(name = "ENROLLRQ", required = true)
    protected EnrollRequest enrollrq;

    /**
     * Gets the value of the enrollrq property.
     * 
     * @return
     *     possible object is
     *     {@link EnrollRequest }
     *     
     */
    public EnrollRequest getENROLLRQ() {
        return enrollrq;
    }

    /**
     * Sets the value of the enrollrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnrollRequest }
     *     
     */
    public void setENROLLRQ(EnrollRequest value) {
        this.enrollrq = value;
    }

}
