//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "SECINFO" is of type "GeneralSecurityInfo"
 *       
 * 
 * <p>Java class for GeneralSecurityInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeneralSecurityInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SECID" type="{http://ofx.net/types/2003/04}SecurityId"/>
 *         &lt;element name="SECNAME" type="{http://ofx.net/types/2003/04}SecurityNameType"/>
 *         &lt;element name="TICKER" type="{http://ofx.net/types/2003/04}TickerType" minOccurs="0"/>
 *         &lt;element name="FIID" type="{http://ofx.net/types/2003/04}FinancialInstitutionIdType" minOccurs="0"/>
 *         &lt;element name="RATING" type="{http://ofx.net/types/2003/04}Rating" minOccurs="0"/>
 *         &lt;element name="UNITPRICE" type="{http://ofx.net/types/2003/04}UnitPriceType" minOccurs="0"/>
 *         &lt;element name="DTASOF" type="{http://ofx.net/types/2003/04}DateTimeType" minOccurs="0"/>
 *         &lt;element name="CURRENCY" type="{http://ofx.net/types/2003/04}Currency" minOccurs="0"/>
 *         &lt;element name="MEMO" type="{http://ofx.net/types/2003/04}MessageType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneralSecurityInfo", propOrder = {
    "secid",
    "secname",
    "ticker",
    "fiid",
    "rating",
    "unitprice",
    "dtasof",
    "currency",
    "memo"
})
public class GeneralSecurityInfo {

    @XmlElement(name = "SECID", required = true)
    protected SecurityId secid;
    @XmlElement(name = "SECNAME", required = true)
    protected String secname;
    @XmlElement(name = "TICKER")
    protected String ticker;
    @XmlElement(name = "FIID")
    protected String fiid;
    @XmlElement(name = "RATING")
    protected String rating;
    @XmlElement(name = "UNITPRICE")
    protected String unitprice;
    @XmlElement(name = "DTASOF")
    protected String dtasof;
    @XmlElement(name = "CURRENCY")
    protected Currency currency;
    @XmlElement(name = "MEMO")
    protected String memo;

    /**
     * Gets the value of the secid property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityId }
     *     
     */
    public SecurityId getSECID() {
        return secid;
    }

    /**
     * Sets the value of the secid property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityId }
     *     
     */
    public void setSECID(SecurityId value) {
        this.secid = value;
    }

    /**
     * Gets the value of the secname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECNAME() {
        return secname;
    }

    /**
     * Sets the value of the secname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECNAME(String value) {
        this.secname = value;
    }

    /**
     * Gets the value of the ticker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTICKER() {
        return ticker;
    }

    /**
     * Sets the value of the ticker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTICKER(String value) {
        this.ticker = value;
    }

    /**
     * Gets the value of the fiid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIID() {
        return fiid;
    }

    /**
     * Sets the value of the fiid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIID(String value) {
        this.fiid = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRATING() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRATING(String value) {
        this.rating = value;
    }

    /**
     * Gets the value of the unitprice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNITPRICE() {
        return unitprice;
    }

    /**
     * Sets the value of the unitprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNITPRICE(String value) {
        this.unitprice = value;
    }

    /**
     * Gets the value of the dtasof property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTASOF() {
        return dtasof;
    }

    /**
     * Sets the value of the dtasof property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTASOF(String value) {
        this.dtasof = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getCURRENCY() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setCURRENCY(Currency value) {
        this.currency = value;
    }

    /**
     * Gets the value of the memo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEMO() {
        return memo;
    }

    /**
     * Sets the value of the memo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEMO(String value) {
        this.memo = value;
    }

}
