//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "INVSELL" is of type "InvestmentSell"
 *       
 * 
 * <p>Java class for InvestmentSell complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvestmentSell">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractInvestmentTransaction">
 *       &lt;sequence>
 *         &lt;element name="SECID" type="{http://ofx.net/types/2003/04}SecurityId"/>
 *         &lt;element name="UNITS" type="{http://ofx.net/types/2003/04}QuantityType"/>
 *         &lt;element name="UNITPRICE" type="{http://ofx.net/types/2003/04}UnitPriceType"/>
 *         &lt;element name="MARKDOWN" type="{http://ofx.net/types/2003/04}UnitPriceType" minOccurs="0"/>
 *         &lt;element name="COMMISSION" type="{http://ofx.net/types/2003/04}PositiveAmountType" minOccurs="0"/>
 *         &lt;element name="TAXES" type="{http://ofx.net/types/2003/04}PositiveAmountType" minOccurs="0"/>
 *         &lt;element name="FEES" type="{http://ofx.net/types/2003/04}PositiveAmountType" minOccurs="0"/>
 *         &lt;element name="LOAD" type="{http://ofx.net/types/2003/04}PositiveAmountType" minOccurs="0"/>
 *         &lt;element name="WITHHOLDING" type="{http://ofx.net/types/2003/04}PositiveAmountType" minOccurs="0"/>
 *         &lt;element name="TAXEXEMPT" type="{http://ofx.net/types/2003/04}BooleanType" minOccurs="0"/>
 *         &lt;element name="TOTAL" type="{http://ofx.net/types/2003/04}AmountType"/>
 *         &lt;element name="GAIN" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="CURRENCY" type="{http://ofx.net/types/2003/04}Currency" minOccurs="0"/>
 *         &lt;element name="ORIGCURRENCY" type="{http://ofx.net/types/2003/04}Currency" minOccurs="0"/>
 *         &lt;element name="SUBACCTSEC" type="{http://ofx.net/types/2003/04}SubAccountEnum"/>
 *         &lt;element name="SUBACCTFUND" type="{http://ofx.net/types/2003/04}SubAccountEnum"/>
 *         &lt;element name="LOANID" type="{http://ofx.net/types/2003/04}LoanIdType" minOccurs="0"/>
 *         &lt;element name="STATEWITHHOLDING" type="{http://ofx.net/types/2003/04}PositiveAmountType" minOccurs="0"/>
 *         &lt;element name="PENALTY" type="{http://ofx.net/types/2003/04}PositiveAmountType" minOccurs="0"/>
 *         &lt;element name="INV401KSOURCE" type="{http://ofx.net/types/2003/04}Investment401kSourceEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvestmentSell", propOrder = {
    "secid",
    "units",
    "unitprice",
    "markdown",
    "commission",
    "taxes",
    "fees",
    "load",
    "withholding",
    "taxexempt",
    "total",
    "gain",
    "currency",
    "origcurrency",
    "subacctsec",
    "subacctfund",
    "loanid",
    "statewithholding",
    "penalty",
    "inv401KSOURCE"
})
public class InvestmentSell
    extends AbstractInvestmentTransaction
{

    @XmlElement(name = "SECID", required = true)
    protected SecurityId secid;
    @XmlElement(name = "UNITS", required = true)
    protected String units;
    @XmlElement(name = "UNITPRICE", required = true)
    protected String unitprice;
    @XmlElement(name = "MARKDOWN")
    protected String markdown;
    @XmlElement(name = "COMMISSION")
    protected String commission;
    @XmlElement(name = "TAXES")
    protected String taxes;
    @XmlElement(name = "FEES")
    protected String fees;
    @XmlElement(name = "LOAD")
    protected String load;
    @XmlElement(name = "WITHHOLDING")
    protected String withholding;
    @XmlElement(name = "TAXEXEMPT")
    protected BooleanType taxexempt;
    @XmlElement(name = "TOTAL", required = true)
    protected String total;
    @XmlElement(name = "GAIN")
    protected String gain;
    @XmlElement(name = "CURRENCY")
    protected Currency currency;
    @XmlElement(name = "ORIGCURRENCY")
    protected Currency origcurrency;
    @XmlElement(name = "SUBACCTSEC", required = true)
    protected SubAccountEnum subacctsec;
    @XmlElement(name = "SUBACCTFUND", required = true)
    protected SubAccountEnum subacctfund;
    @XmlElement(name = "LOANID")
    protected String loanid;
    @XmlElement(name = "STATEWITHHOLDING")
    protected String statewithholding;
    @XmlElement(name = "PENALTY")
    protected String penalty;
    @XmlElement(name = "INV401KSOURCE")
    protected Investment401KSourceEnum inv401KSOURCE;

    /**
     * Gets the value of the secid property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityId }
     *     
     */
    public SecurityId getSECID() {
        return secid;
    }

    /**
     * Sets the value of the secid property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityId }
     *     
     */
    public void setSECID(SecurityId value) {
        this.secid = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNITS() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNITS(String value) {
        this.units = value;
    }

    /**
     * Gets the value of the unitprice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNITPRICE() {
        return unitprice;
    }

    /**
     * Sets the value of the unitprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNITPRICE(String value) {
        this.unitprice = value;
    }

    /**
     * Gets the value of the markdown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMARKDOWN() {
        return markdown;
    }

    /**
     * Sets the value of the markdown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMARKDOWN(String value) {
        this.markdown = value;
    }

    /**
     * Gets the value of the commission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMMISSION() {
        return commission;
    }

    /**
     * Sets the value of the commission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMMISSION(String value) {
        this.commission = value;
    }

    /**
     * Gets the value of the taxes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXES() {
        return taxes;
    }

    /**
     * Sets the value of the taxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXES(String value) {
        this.taxes = value;
    }

    /**
     * Gets the value of the fees property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFEES() {
        return fees;
    }

    /**
     * Sets the value of the fees property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFEES(String value) {
        this.fees = value;
    }

    /**
     * Gets the value of the load property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOAD() {
        return load;
    }

    /**
     * Sets the value of the load property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOAD(String value) {
        this.load = value;
    }

    /**
     * Gets the value of the withholding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWITHHOLDING() {
        return withholding;
    }

    /**
     * Sets the value of the withholding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWITHHOLDING(String value) {
        this.withholding = value;
    }

    /**
     * Gets the value of the taxexempt property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getTAXEXEMPT() {
        return taxexempt;
    }

    /**
     * Sets the value of the taxexempt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setTAXEXEMPT(BooleanType value) {
        this.taxexempt = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTAL() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTAL(String value) {
        this.total = value;
    }

    /**
     * Gets the value of the gain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGAIN() {
        return gain;
    }

    /**
     * Sets the value of the gain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGAIN(String value) {
        this.gain = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getCURRENCY() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setCURRENCY(Currency value) {
        this.currency = value;
    }

    /**
     * Gets the value of the origcurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getORIGCURRENCY() {
        return origcurrency;
    }

    /**
     * Sets the value of the origcurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setORIGCURRENCY(Currency value) {
        this.origcurrency = value;
    }

    /**
     * Gets the value of the subacctsec property.
     * 
     * @return
     *     possible object is
     *     {@link SubAccountEnum }
     *     
     */
    public SubAccountEnum getSUBACCTSEC() {
        return subacctsec;
    }

    /**
     * Sets the value of the subacctsec property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubAccountEnum }
     *     
     */
    public void setSUBACCTSEC(SubAccountEnum value) {
        this.subacctsec = value;
    }

    /**
     * Gets the value of the subacctfund property.
     * 
     * @return
     *     possible object is
     *     {@link SubAccountEnum }
     *     
     */
    public SubAccountEnum getSUBACCTFUND() {
        return subacctfund;
    }

    /**
     * Sets the value of the subacctfund property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubAccountEnum }
     *     
     */
    public void setSUBACCTFUND(SubAccountEnum value) {
        this.subacctfund = value;
    }

    /**
     * Gets the value of the loanid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOANID() {
        return loanid;
    }

    /**
     * Sets the value of the loanid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOANID(String value) {
        this.loanid = value;
    }

    /**
     * Gets the value of the statewithholding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATEWITHHOLDING() {
        return statewithholding;
    }

    /**
     * Sets the value of the statewithholding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATEWITHHOLDING(String value) {
        this.statewithholding = value;
    }

    /**
     * Gets the value of the penalty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPENALTY() {
        return penalty;
    }

    /**
     * Sets the value of the penalty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPENALTY(String value) {
        this.penalty = value;
    }

    /**
     * Gets the value of the inv401KSOURCE property.
     * 
     * @return
     *     possible object is
     *     {@link Investment401KSourceEnum }
     *     
     */
    public Investment401KSourceEnum getINV401KSOURCE() {
        return inv401KSOURCE;
    }

    /**
     * Sets the value of the inv401KSOURCE property.
     * 
     * @param value
     *     allowed object is
     *     {@link Investment401KSourceEnum }
     *     
     */
    public void setINV401KSOURCE(Investment401KSourceEnum value) {
        this.inv401KSOURCE = value;
    }

}
