//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "INVOICE" is of type "Invoice"
 *       
 * 
 * <p>Java class for Invoice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Invoice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="INVNO" type="{http://ofx.net/types/2003/04}InvestmentNumberType"/>
 *         &lt;element name="INVTOTALAMT" type="{http://ofx.net/types/2003/04}AmountType"/>
 *         &lt;element name="INVPAIDAMT" type="{http://ofx.net/types/2003/04}AmountType"/>
 *         &lt;element name="INVDATE" type="{http://ofx.net/types/2003/04}DateTimeType"/>
 *         &lt;element name="INVDESC" type="{http://ofx.net/types/2003/04}ShortMessageType"/>
 *         &lt;element name="DISCOUNT" type="{http://ofx.net/types/2003/04}Discount" minOccurs="0"/>
 *         &lt;element name="ADJUSTMENT" type="{http://ofx.net/types/2003/04}Adjustment" minOccurs="0"/>
 *         &lt;element name="LINEITEM" type="{http://ofx.net/types/2003/04}LineItem" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Invoice", propOrder = {
    "invno",
    "invtotalamt",
    "invpaidamt",
    "invdate",
    "invdesc",
    "discount",
    "adjustment",
    "lineitem"
})
public class Invoice {

    @XmlElement(name = "INVNO", required = true)
    protected String invno;
    @XmlElement(name = "INVTOTALAMT", required = true)
    protected String invtotalamt;
    @XmlElement(name = "INVPAIDAMT", required = true)
    protected String invpaidamt;
    @XmlElement(name = "INVDATE", required = true)
    protected String invdate;
    @XmlElement(name = "INVDESC", required = true)
    protected String invdesc;
    @XmlElement(name = "DISCOUNT")
    protected Discount discount;
    @XmlElement(name = "ADJUSTMENT")
    protected Adjustment adjustment;
    @XmlElement(name = "LINEITEM")
    protected List<LineItem> lineitem;

    /**
     * Gets the value of the invno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVNO() {
        return invno;
    }

    /**
     * Sets the value of the invno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVNO(String value) {
        this.invno = value;
    }

    /**
     * Gets the value of the invtotalamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVTOTALAMT() {
        return invtotalamt;
    }

    /**
     * Sets the value of the invtotalamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVTOTALAMT(String value) {
        this.invtotalamt = value;
    }

    /**
     * Gets the value of the invpaidamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVPAIDAMT() {
        return invpaidamt;
    }

    /**
     * Sets the value of the invpaidamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVPAIDAMT(String value) {
        this.invpaidamt = value;
    }

    /**
     * Gets the value of the invdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVDATE() {
        return invdate;
    }

    /**
     * Sets the value of the invdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVDATE(String value) {
        this.invdate = value;
    }

    /**
     * Gets the value of the invdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVDESC() {
        return invdesc;
    }

    /**
     * Sets the value of the invdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVDESC(String value) {
        this.invdesc = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link Discount }
     *     
     */
    public Discount getDISCOUNT() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Discount }
     *     
     */
    public void setDISCOUNT(Discount value) {
        this.discount = value;
    }

    /**
     * Gets the value of the adjustment property.
     * 
     * @return
     *     possible object is
     *     {@link Adjustment }
     *     
     */
    public Adjustment getADJUSTMENT() {
        return adjustment;
    }

    /**
     * Sets the value of the adjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Adjustment }
     *     
     */
    public void setADJUSTMENT(Adjustment value) {
        this.adjustment = value;
    }

    /**
     * Gets the value of the lineitem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineitem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLINEITEM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineItem }
     * 
     * 
     */
    public List<LineItem> getLINEITEM() {
        if (lineitem == null) {
            lineitem = new ArrayList<LineItem>();
        }
        return this.lineitem;
    }

}
