//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "LCLTAXWHAGG" is of type "LocalTaxWithheldAggregate"
 *       
 * 
 * <p>Java class for LocalTaxWithheldAggregate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocalTaxWithheldAggregate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AMOUNT" type="{http://ofx.net/types/2003/04}AmountType"/>
 *         &lt;element name="NAMELCL" type="{http://ofx.net/types/2003/04}GenericNameType"/>
 *         &lt;element name="LCLDIST" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocalTaxWithheldAggregate", propOrder = {
    "amount",
    "namelcl",
    "lcldist"
})
public class LocalTaxWithheldAggregate {

    @XmlElement(name = "AMOUNT", required = true)
    protected String amount;
    @XmlElement(name = "NAMELCL", required = true)
    protected String namelcl;
    @XmlElement(name = "LCLDIST")
    protected String lcldist;

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMOUNT() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMOUNT(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the namelcl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAMELCL() {
        return namelcl;
    }

    /**
     * Sets the value of the namelcl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAMELCL(String value) {
        this.namelcl = value;
    }

    /**
     * Gets the value of the lcldist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLCLDIST() {
        return lcldist;
    }

    /**
     * Sets the value of the lcldist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLCLDIST(String value) {
        this.lcldist = value;
    }

}
