//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "MFACHALLENGEANSWER" is of type "MFAChallengeAnswer".
 *       
 * 
 * <p>Java class for MFAChallengeAnswer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MFAChallengeAnswer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MFAPHRASEID" type="{http://ofx.net/types/2003/04}IdType"/>
 *         &lt;element name="MFAPHRASEA" type="{http://ofx.net/types/2003/04}MFAPhraseType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MFAChallengeAnswer", propOrder = {
    "mfaphraseid",
    "mfaphrasea"
})
public class MFAChallengeAnswer {

    @XmlElement(name = "MFAPHRASEID", required = true)
    protected String mfaphraseid;
    @XmlElement(name = "MFAPHRASEA", required = true)
    protected String mfaphrasea;

    /**
     * Gets the value of the mfaphraseid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMFAPHRASEID() {
        return mfaphraseid;
    }

    /**
     * Sets the value of the mfaphraseid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMFAPHRASEID(String value) {
        this.mfaphraseid = value;
    }

    /**
     * Gets the value of the mfaphrasea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMFAPHRASEA() {
        return mfaphrasea;
    }

    /**
     * Sets the value of the mfaphrasea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMFAPHRASEA(String value) {
        this.mfaphrasea = value;
    }

}
