//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "PMTTRNRQ" is of type "PaymentTransactionRequest"
 *       
 * 
 * <p>Java class for PaymentTransactionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentTransactionRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractTransactionRequest">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="PMTRQ" type="{http://ofx.net/types/2003/04}PaymentRequest"/>
 *           &lt;element name="PMTMODRQ" type="{http://ofx.net/types/2003/04}PaymentModRequest"/>
 *           &lt;element name="PMTCANCRQ" type="{http://ofx.net/types/2003/04}PaymentCancelRequest"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentTransactionRequest", propOrder = {
    "pmtrq",
    "pmtmodrq",
    "pmtcancrq"
})
public class PaymentTransactionRequest
    extends AbstractTransactionRequest
{

    @XmlElement(name = "PMTRQ")
    protected PaymentRequest pmtrq;
    @XmlElement(name = "PMTMODRQ")
    protected PaymentModRequest pmtmodrq;
    @XmlElement(name = "PMTCANCRQ")
    protected PaymentCancelRequest pmtcancrq;

    /**
     * Gets the value of the pmtrq property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentRequest }
     *     
     */
    public PaymentRequest getPMTRQ() {
        return pmtrq;
    }

    /**
     * Sets the value of the pmtrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentRequest }
     *     
     */
    public void setPMTRQ(PaymentRequest value) {
        this.pmtrq = value;
    }

    /**
     * Gets the value of the pmtmodrq property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentModRequest }
     *     
     */
    public PaymentModRequest getPMTMODRQ() {
        return pmtmodrq;
    }

    /**
     * Sets the value of the pmtmodrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentModRequest }
     *     
     */
    public void setPMTMODRQ(PaymentModRequest value) {
        this.pmtmodrq = value;
    }

    /**
     * Gets the value of the pmtcancrq property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentCancelRequest }
     *     
     */
    public PaymentCancelRequest getPMTCANCRQ() {
        return pmtcancrq;
    }

    /**
     * Sets the value of the pmtcancrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentCancelRequest }
     *     
     */
    public void setPMTCANCRQ(PaymentCancelRequest value) {
        this.pmtcancrq = value;
    }

}
