//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentInstrumentEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PaymentInstrumentEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="CONCENTRATOR"/>
 *     &lt;enumeration value="CHECKINGACCOUNT"/>
 *     &lt;enumeration value="CREDITCARD"/>
 *     &lt;enumeration value="ECOIN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PaymentInstrumentEnum")
@XmlEnum
public enum PaymentInstrumentEnum {

    CONCENTRATOR,
    CHECKINGACCOUNT,
    CREDITCARD,
    ECOIN;

    public String value() {
        return name();
    }

    public static PaymentInstrumentEnum fromValue(String v) {
        return valueOf(v);
    }

}
