//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "PINCHTRNRQ" is of type "PinChangeTransactionRequest"
 *       
 * 
 * <p>Java class for PinChangeTransactionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PinChangeTransactionRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractTransactionRequest">
 *       &lt;sequence>
 *         &lt;element name="PINCHRQ" type="{http://ofx.net/types/2003/04}PinChangeRequest"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PinChangeTransactionRequest", propOrder = {
    "pinchrq"
})
public class PinChangeTransactionRequest
    extends AbstractTransactionRequest
{

    @XmlElement(name = "PINCHRQ", required = true)
    protected PinChangeRequest pinchrq;

    /**
     * Gets the value of the pinchrq property.
     * 
     * @return
     *     possible object is
     *     {@link PinChangeRequest }
     *     
     */
    public PinChangeRequest getPINCHRQ() {
        return pinchrq;
    }

    /**
     * Sets the value of the pinchrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PinChangeRequest }
     *     
     */
    public void setPINCHRQ(PinChangeRequest value) {
        this.pinchrq = value;
    }

}
