//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "POSOPT" is of type "PositionOption"
 *       
 * 
 * <p>Java class for PositionOption complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PositionOption">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractPositionBase">
 *       &lt;sequence>
 *         &lt;element name="SECURED" type="{http://ofx.net/types/2003/04}SecuredEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PositionOption", propOrder = {
    "secured"
})
public class PositionOption
    extends AbstractPositionBase
{

    @XmlElement(name = "SECURED")
    protected SecuredEnum secured;

    /**
     * Gets the value of the secured property.
     * 
     * @return
     *     possible object is
     *     {@link SecuredEnum }
     *     
     */
    public SecuredEnum getSECURED() {
        return secured;
    }

    /**
     * Sets the value of the secured property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecuredEnum }
     *     
     */
    public void setSECURED(SecuredEnum value) {
        this.secured = value;
    }

}
