//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "PRESDLVMSGSRSV1" is of type "PresentmentDeliveryResponseMessageSetV1"
 *       
 * 
 * <p>Java class for PresentmentDeliveryResponseMessageSetV1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PresentmentDeliveryResponseMessageSetV1">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractResponseMessageSet">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="PRESLISTTRNRS" type="{http://ofx.net/types/2003/04}PresentmentListTransactionResponse"/>
 *         &lt;element name="PRESGRPACCTINFOTRNRS" type="{http://ofx.net/types/2003/04}PresentmentGroupAccountInfoTransactionResponse"/>
 *         &lt;element name="PRESDETAILTRNRS" type="{http://ofx.net/types/2003/04}PresentmentDetailTransactionResponse"/>
 *         &lt;element name="BILLTBLSTRUCTTRNRS" type="{http://ofx.net/types/2003/04}BillTableStructureTransactionResponse"/>
 *         &lt;element name="PRESNOTIFYTRNRS" type="{http://ofx.net/types/2003/04}PresentmentNotifyTransactionResponse"/>
 *         &lt;element name="BILLSTATUSMODTRNRS" type="{http://ofx.net/types/2003/04}BillStatusModTransactionResponse"/>
 *         &lt;element name="PRESMAILSYNCRS" type="{http://ofx.net/types/2003/04}PresentmentMailSyncResponse"/>
 *         &lt;element name="PRESMAILTRNRS" type="{http://ofx.net/types/2003/04}PresentmentMailTransactionResponse"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PresentmentDeliveryResponseMessageSetV1", propOrder = {
    "preslisttrnrsOrPRESGRPACCTINFOTRNRSOrPRESDETAILTRNRS"
})
public class PresentmentDeliveryResponseMessageSetV1
    extends AbstractResponseMessageSet
{

    @XmlElements({
        @XmlElement(name = "PRESLISTTRNRS", type = PresentmentListTransactionResponse.class),
        @XmlElement(name = "PRESGRPACCTINFOTRNRS", type = PresentmentGroupAccountInfoTransactionResponse.class),
        @XmlElement(name = "PRESDETAILTRNRS", type = PresentmentDetailTransactionResponse.class),
        @XmlElement(name = "BILLTBLSTRUCTTRNRS", type = BillTableStructureTransactionResponse.class),
        @XmlElement(name = "PRESNOTIFYTRNRS", type = PresentmentNotifyTransactionResponse.class),
        @XmlElement(name = "BILLSTATUSMODTRNRS", type = BillStatusModTransactionResponse.class),
        @XmlElement(name = "PRESMAILSYNCRS", type = PresentmentMailSyncResponse.class),
        @XmlElement(name = "PRESMAILTRNRS", type = PresentmentMailTransactionResponse.class)
    })
    protected List<AbstractResponse> preslisttrnrsOrPRESGRPACCTINFOTRNRSOrPRESDETAILTRNRS;

    /**
     * Gets the value of the preslisttrnrsOrPRESGRPACCTINFOTRNRSOrPRESDETAILTRNRS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the preslisttrnrsOrPRESGRPACCTINFOTRNRSOrPRESDETAILTRNRS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPRESLISTTRNRSOrPRESGRPACCTINFOTRNRSOrPRESDETAILTRNRS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PresentmentListTransactionResponse }
     * {@link PresentmentGroupAccountInfoTransactionResponse }
     * {@link PresentmentDetailTransactionResponse }
     * {@link BillTableStructureTransactionResponse }
     * {@link PresentmentNotifyTransactionResponse }
     * {@link BillStatusModTransactionResponse }
     * {@link PresentmentMailSyncResponse }
     * {@link PresentmentMailTransactionResponse }
     * 
     * 
     */
    public List<AbstractResponse> getPRESLISTTRNRSOrPRESGRPACCTINFOTRNRSOrPRESDETAILTRNRS() {
        if (preslisttrnrsOrPRESGRPACCTINFOTRNRSOrPRESDETAILTRNRS == null) {
            preslisttrnrsOrPRESGRPACCTINFOTRNRSOrPRESDETAILTRNRS = new ArrayList<AbstractResponse>();
        }
        return this.preslisttrnrsOrPRESGRPACCTINFOTRNRSOrPRESDETAILTRNRS;
    }

}
