//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "PRESDETAILTRNRQ" is of type "PresentmentDetailTransactionRequest"
 *       
 * 
 * <p>Java class for PresentmentDetailTransactionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PresentmentDetailTransactionRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractTransactionRequest">
 *       &lt;sequence>
 *         &lt;element name="PRESDETAILRQ" type="{http://ofx.net/types/2003/04}PresentmentDetailRequest"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PresentmentDetailTransactionRequest", propOrder = {
    "presdetailrq"
})
public class PresentmentDetailTransactionRequest
    extends AbstractTransactionRequest
{

    @XmlElement(name = "PRESDETAILRQ", required = true)
    protected PresentmentDetailRequest presdetailrq;

    /**
     * Gets the value of the presdetailrq property.
     * 
     * @return
     *     possible object is
     *     {@link PresentmentDetailRequest }
     *     
     */
    public PresentmentDetailRequest getPRESDETAILRQ() {
        return presdetailrq;
    }

    /**
     * Sets the value of the presdetailrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PresentmentDetailRequest }
     *     
     */
    public void setPRESDETAILRQ(PresentmentDetailRequest value) {
        this.presdetailrq = value;
    }

}
