//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "PRESACCTFROM" is of type "PresentmentAccount"
 *       
 * 
 * <p>Java class for PresentmentAccount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PresentmentAccount">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractAccount">
 *       &lt;sequence>
 *         &lt;element name="BILLPUB" type="{http://ofx.net/types/2003/04}GenericNameType"/>
 *         &lt;element name="BILLERID" type="{http://ofx.net/types/2003/04}IdType"/>
 *         &lt;element name="BILLERNAME" type="{http://ofx.net/types/2003/04}GenericNameType" minOccurs="0"/>
 *         &lt;element name="ACCTID" type="{http://ofx.net/types/2003/04}AccountIdType"/>
 *         &lt;element name="PRESNAMEADDRESS" type="{http://ofx.net/types/2003/04}PresentmentNameAddress" minOccurs="0"/>
 *         &lt;element name="USERID" type="{http://ofx.net/types/2003/04}IdType" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="SPNAME" type="{http://ofx.net/types/2003/04}GenericNameType" minOccurs="0"/>
 *           &lt;choice>
 *             &lt;sequence>
 *               &lt;element name="PAYEEID" type="{http://ofx.net/types/2003/04}PayeeIdType"/>
 *               &lt;element name="PAYEELSTID" type="{http://ofx.net/types/2003/04}PayeeIdType" minOccurs="0"/>
 *             &lt;/sequence>
 *             &lt;element name="PAYEELSTID" type="{http://ofx.net/types/2003/04}PayeeIdType"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PresentmentAccount", propOrder = {
    "rest"
})
public class PresentmentAccount
    extends AbstractAccount
{

    @XmlElementRefs({
        @XmlElementRef(name = "SPNAME", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "USERID", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ACCTID", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PAYEEID", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BILLERNAME", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BILLPUB", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PAYEELSTID", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PRESNAMEADDRESS", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BILLERID", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> rest;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "PAYEELSTID" is used by two different parts of a schema. See: 
     * line 1828 of file:/C:/Users/pierrero/workspace/OFXGeneration/OFX%202.0.3%20Schema/OFX_Common.xsd
     * line 1826 of file:/C:/Users/pierrero/workspace/OFXGeneration/OFX%202.0.3%20Schema/OFX_Common.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the rest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link PresentmentNameAddress }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getRest() {
        if (rest == null) {
            rest = new ArrayList<JAXBElement<?>>();
        }
        return this.rest;
    }

}
