//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "PRESDIRMSGSETV1" is of type "PresentmentDirMessageSetV1"
 *       
 * 
 * <p>Java class for PresentmentDirMessageSetV1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PresentmentDirMessageSetV1">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractMessageSetVersion">
 *       &lt;sequence>
 *         &lt;element name="PRESDIRPROF" type="{http://ofx.net/types/2003/04}PresentmentDirProfile" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PresentmentDirMessageSetV1", propOrder = {
    "presdirprof"
})
public class PresentmentDirMessageSetV1
    extends AbstractMessageSetVersion
{

    @XmlElement(name = "PRESDIRPROF")
    protected PresentmentDirProfile presdirprof;

    /**
     * Gets the value of the presdirprof property.
     * 
     * @return
     *     possible object is
     *     {@link PresentmentDirProfile }
     *     
     */
    public PresentmentDirProfile getPRESDIRPROF() {
        return presdirprof;
    }

    /**
     * Sets the value of the presdirprof property.
     * 
     * @param value
     *     allowed object is
     *     {@link PresentmentDirProfile }
     *     
     */
    public void setPRESDIRPROF(PresentmentDirProfile value) {
        this.presdirprof = value;
    }

}
