//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "RECPMTTRNRQ" is of type "RecurringPaymentTransactionRequest"
 *       
 * 
 * <p>Java class for RecurringPaymentTransactionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecurringPaymentTransactionRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractTransactionRequest">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="RECPMTRQ" type="{http://ofx.net/types/2003/04}RecurringPaymentRequest"/>
 *           &lt;element name="RECPMTMODRQ" type="{http://ofx.net/types/2003/04}RecurringPaymentModRequest"/>
 *           &lt;element name="RECPMTCANCRQ" type="{http://ofx.net/types/2003/04}RecurringPaymentCancelRequest"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecurringPaymentTransactionRequest", propOrder = {
    "recpmtrq",
    "recpmtmodrq",
    "recpmtcancrq"
})
public class RecurringPaymentTransactionRequest
    extends AbstractTransactionRequest
{

    @XmlElement(name = "RECPMTRQ")
    protected RecurringPaymentRequest recpmtrq;
    @XmlElement(name = "RECPMTMODRQ")
    protected RecurringPaymentModRequest recpmtmodrq;
    @XmlElement(name = "RECPMTCANCRQ")
    protected RecurringPaymentCancelRequest recpmtcancrq;

    /**
     * Gets the value of the recpmtrq property.
     * 
     * @return
     *     possible object is
     *     {@link RecurringPaymentRequest }
     *     
     */
    public RecurringPaymentRequest getRECPMTRQ() {
        return recpmtrq;
    }

    /**
     * Sets the value of the recpmtrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecurringPaymentRequest }
     *     
     */
    public void setRECPMTRQ(RecurringPaymentRequest value) {
        this.recpmtrq = value;
    }

    /**
     * Gets the value of the recpmtmodrq property.
     * 
     * @return
     *     possible object is
     *     {@link RecurringPaymentModRequest }
     *     
     */
    public RecurringPaymentModRequest getRECPMTMODRQ() {
        return recpmtmodrq;
    }

    /**
     * Sets the value of the recpmtmodrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecurringPaymentModRequest }
     *     
     */
    public void setRECPMTMODRQ(RecurringPaymentModRequest value) {
        this.recpmtmodrq = value;
    }

    /**
     * Gets the value of the recpmtcancrq property.
     * 
     * @return
     *     possible object is
     *     {@link RecurringPaymentCancelRequest }
     *     
     */
    public RecurringPaymentCancelRequest getRECPMTCANCRQ() {
        return recpmtcancrq;
    }

    /**
     * Sets the value of the recpmtcancrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecurringPaymentCancelRequest }
     *     
     */
    public void setRECPMTCANCRQ(RecurringPaymentCancelRequest value) {
        this.recpmtcancrq = value;
    }

}
