//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "RECINTERTRNRS" is of type "RecurringInterTransactionResponse"
 *       
 * 
 * <p>Java class for RecurringInterTransactionResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecurringInterTransactionResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractTransactionResponse">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="RECINTERRS" type="{http://ofx.net/types/2003/04}RecurringInterResponse"/>
 *           &lt;element name="RECINTERMODRS" type="{http://ofx.net/types/2003/04}RecurringInterModResponse"/>
 *           &lt;element name="RECINTERCANRS" type="{http://ofx.net/types/2003/04}RecurringInterCancellationResponse"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecurringInterTransactionResponse", propOrder = {
    "recinterrs",
    "recintermodrs",
    "recintercanrs"
})
public class RecurringInterTransactionResponse
    extends AbstractTransactionResponse
{

    @XmlElement(name = "RECINTERRS")
    protected RecurringInterResponse recinterrs;
    @XmlElement(name = "RECINTERMODRS")
    protected RecurringInterModResponse recintermodrs;
    @XmlElement(name = "RECINTERCANRS")
    protected RecurringInterCancellationResponse recintercanrs;

    /**
     * Gets the value of the recinterrs property.
     * 
     * @return
     *     possible object is
     *     {@link RecurringInterResponse }
     *     
     */
    public RecurringInterResponse getRECINTERRS() {
        return recinterrs;
    }

    /**
     * Sets the value of the recinterrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecurringInterResponse }
     *     
     */
    public void setRECINTERRS(RecurringInterResponse value) {
        this.recinterrs = value;
    }

    /**
     * Gets the value of the recintermodrs property.
     * 
     * @return
     *     possible object is
     *     {@link RecurringInterModResponse }
     *     
     */
    public RecurringInterModResponse getRECINTERMODRS() {
        return recintermodrs;
    }

    /**
     * Sets the value of the recintermodrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecurringInterModResponse }
     *     
     */
    public void setRECINTERMODRS(RecurringInterModResponse value) {
        this.recintermodrs = value;
    }

    /**
     * Gets the value of the recintercanrs property.
     * 
     * @return
     *     possible object is
     *     {@link RecurringInterCancellationResponse }
     *     
     */
    public RecurringInterCancellationResponse getRECINTERCANRS() {
        return recintercanrs;
    }

    /**
     * Sets the value of the recintercanrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecurringInterCancellationResponse }
     *     
     */
    public void setRECINTERCANRS(RecurringInterCancellationResponse value) {
        this.recintercanrs = value;
    }

}
