//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "RECURRINST" is of type "RecurringInstructions"
 *       
 * 
 * <p>Java class for RecurringInstructions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecurringInstructions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NINSTS" type="{http://ofx.net/types/2003/04}NumberOfInstructionsType" minOccurs="0"/>
 *         &lt;element name="FREQ" type="{http://ofx.net/types/2003/04}FrequencyEnum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecurringInstructions", propOrder = {
    "ninsts",
    "freq"
})
public class RecurringInstructions {

    @XmlElement(name = "NINSTS")
    protected String ninsts;
    @XmlElement(name = "FREQ", required = true)
    protected FrequencyEnum freq;

    /**
     * Gets the value of the ninsts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNINSTS() {
        return ninsts;
    }

    /**
     * Sets the value of the ninsts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNINSTS(String value) {
        this.ninsts = value;
    }

    /**
     * Gets the value of the freq property.
     * 
     * @return
     *     possible object is
     *     {@link FrequencyEnum }
     *     
     */
    public FrequencyEnum getFREQ() {
        return freq;
    }

    /**
     * Sets the value of the freq property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrequencyEnum }
     *     
     */
    public void setFREQ(FrequencyEnum value) {
        this.freq = value;
    }

}
