//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "RECINTERRQ" is of type "RecurringInterRequest"
 *       
 * 
 * <p>Java class for RecurringInterRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecurringInterRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractRecurringInterRequest">
 *       &lt;sequence>
 *         &lt;element name="RECURRINST" type="{http://ofx.net/types/2003/04}RecurringInstructions"/>
 *         &lt;element name="INTERRQ" type="{http://ofx.net/types/2003/04}InterRequest"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecurringInterRequest", propOrder = {
    "recurrinst",
    "interrq"
})
public class RecurringInterRequest
    extends AbstractRecurringInterRequest
{

    @XmlElement(name = "RECURRINST", required = true)
    protected RecurringInstructions recurrinst;
    @XmlElement(name = "INTERRQ", required = true)
    protected InterRequest interrq;

    /**
     * Gets the value of the recurrinst property.
     * 
     * @return
     *     possible object is
     *     {@link RecurringInstructions }
     *     
     */
    public RecurringInstructions getRECURRINST() {
        return recurrinst;
    }

    /**
     * Sets the value of the recurrinst property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecurringInstructions }
     *     
     */
    public void setRECURRINST(RecurringInstructions value) {
        this.recurrinst = value;
    }

    /**
     * Gets the value of the interrq property.
     * 
     * @return
     *     possible object is
     *     {@link InterRequest }
     *     
     */
    public InterRequest getINTERRQ() {
        return interrq;
    }

    /**
     * Sets the value of the interrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterRequest }
     *     
     */
    public void setINTERRQ(InterRequest value) {
        this.interrq = value;
    }

}
