//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "SELLDEBT" is of type "SellDebt"
 *       
 * 
 * <p>Java class for SellDebt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SellDebt">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractInvestmentSellTransaction">
 *       &lt;sequence>
 *         &lt;element name="SELLREASON" type="{http://ofx.net/types/2003/04}SellReasonEnum"/>
 *         &lt;element name="ACCRDINT" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SellDebt", propOrder = {
    "sellreason",
    "accrdint"
})
public class SellDebt
    extends AbstractInvestmentSellTransaction
{

    @XmlElement(name = "SELLREASON", required = true)
    protected SellReasonEnum sellreason;
    @XmlElement(name = "ACCRDINT")
    protected String accrdint;

    /**
     * Gets the value of the sellreason property.
     * 
     * @return
     *     possible object is
     *     {@link SellReasonEnum }
     *     
     */
    public SellReasonEnum getSELLREASON() {
        return sellreason;
    }

    /**
     * Sets the value of the sellreason property.
     * 
     * @param value
     *     allowed object is
     *     {@link SellReasonEnum }
     *     
     */
    public void setSELLREASON(SellReasonEnum value) {
        this.sellreason = value;
    }

    /**
     * Gets the value of the accrdint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCRDINT() {
        return accrdint;
    }

    /**
     * Sets the value of the accrdint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCRDINT(String value) {
        this.accrdint = value;
    }

}
