//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *               The OFX element "SVCDEL" is of type "ServiceDelete"
 *             
 * 
 * <p>Java class for ServiceDelete complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceDelete">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractServiceAction">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="BANKACCTFROM" type="{http://ofx.net/types/2003/04}BankAccount"/>
 *           &lt;element name="CCACCTFROM" type="{http://ofx.net/types/2003/04}CreditCardAccount"/>
 *           &lt;element name="INVACCTFROM" type="{http://ofx.net/types/2003/04}InvestmentAccount"/>
 *           &lt;element name="PRESACCTFROM" type="{http://ofx.net/types/2003/04}PresentmentAccount"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceDelete", propOrder = {
    "bankacctfrom",
    "ccacctfrom",
    "invacctfrom",
    "presacctfrom"
})
public class ServiceDelete
    extends AbstractServiceAction
{

    @XmlElement(name = "BANKACCTFROM")
    protected BankAccount bankacctfrom;
    @XmlElement(name = "CCACCTFROM")
    protected CreditCardAccount ccacctfrom;
    @XmlElement(name = "INVACCTFROM")
    protected InvestmentAccount invacctfrom;
    @XmlElement(name = "PRESACCTFROM")
    protected PresentmentAccount presacctfrom;

    /**
     * Gets the value of the bankacctfrom property.
     * 
     * @return
     *     possible object is
     *     {@link BankAccount }
     *     
     */
    public BankAccount getBANKACCTFROM() {
        return bankacctfrom;
    }

    /**
     * Sets the value of the bankacctfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankAccount }
     *     
     */
    public void setBANKACCTFROM(BankAccount value) {
        this.bankacctfrom = value;
    }

    /**
     * Gets the value of the ccacctfrom property.
     * 
     * @return
     *     possible object is
     *     {@link CreditCardAccount }
     *     
     */
    public CreditCardAccount getCCACCTFROM() {
        return ccacctfrom;
    }

    /**
     * Sets the value of the ccacctfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditCardAccount }
     *     
     */
    public void setCCACCTFROM(CreditCardAccount value) {
        this.ccacctfrom = value;
    }

    /**
     * Gets the value of the invacctfrom property.
     * 
     * @return
     *     possible object is
     *     {@link InvestmentAccount }
     *     
     */
    public InvestmentAccount getINVACCTFROM() {
        return invacctfrom;
    }

    /**
     * Sets the value of the invacctfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvestmentAccount }
     *     
     */
    public void setINVACCTFROM(InvestmentAccount value) {
        this.invacctfrom = value;
    }

    /**
     * Gets the value of the presacctfrom property.
     * 
     * @return
     *     possible object is
     *     {@link PresentmentAccount }
     *     
     */
    public PresentmentAccount getPRESACCTFROM() {
        return presacctfrom;
    }

    /**
     * Sets the value of the presacctfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link PresentmentAccount }
     *     
     */
    public void setPRESACCTFROM(PresentmentAccount value) {
        this.presacctfrom = value;
    }

}
