//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *               The OFX element "SVCADD" is of type "ServiceAdd"
 *             
 * 
 * <p>Java class for ServiceAdd complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceAdd">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractServiceAction">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="BANKACCTTO" type="{http://ofx.net/types/2003/04}BankAccount"/>
 *           &lt;element name="CCACCTTO" type="{http://ofx.net/types/2003/04}CreditCardAccount"/>
 *           &lt;element name="INVACCTTO" type="{http://ofx.net/types/2003/04}InvestmentAccount"/>
 *           &lt;element name="PRESACCTTO" type="{http://ofx.net/types/2003/04}PresentmentAccount"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceAdd", propOrder = {
    "bankacctto",
    "ccacctto",
    "invacctto",
    "presacctto"
})
public class ServiceAdd
    extends AbstractServiceAction
{

    @XmlElement(name = "BANKACCTTO")
    protected BankAccount bankacctto;
    @XmlElement(name = "CCACCTTO")
    protected CreditCardAccount ccacctto;
    @XmlElement(name = "INVACCTTO")
    protected InvestmentAccount invacctto;
    @XmlElement(name = "PRESACCTTO")
    protected PresentmentAccount presacctto;

    /**
     * Gets the value of the bankacctto property.
     * 
     * @return
     *     possible object is
     *     {@link BankAccount }
     *     
     */
    public BankAccount getBANKACCTTO() {
        return bankacctto;
    }

    /**
     * Sets the value of the bankacctto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankAccount }
     *     
     */
    public void setBANKACCTTO(BankAccount value) {
        this.bankacctto = value;
    }

    /**
     * Gets the value of the ccacctto property.
     * 
     * @return
     *     possible object is
     *     {@link CreditCardAccount }
     *     
     */
    public CreditCardAccount getCCACCTTO() {
        return ccacctto;
    }

    /**
     * Sets the value of the ccacctto property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditCardAccount }
     *     
     */
    public void setCCACCTTO(CreditCardAccount value) {
        this.ccacctto = value;
    }

    /**
     * Gets the value of the invacctto property.
     * 
     * @return
     *     possible object is
     *     {@link InvestmentAccount }
     *     
     */
    public InvestmentAccount getINVACCTTO() {
        return invacctto;
    }

    /**
     * Sets the value of the invacctto property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvestmentAccount }
     *     
     */
    public void setINVACCTTO(InvestmentAccount value) {
        this.invacctto = value;
    }

    /**
     * Gets the value of the presacctto property.
     * 
     * @return
     *     possible object is
     *     {@link PresentmentAccount }
     *     
     */
    public PresentmentAccount getPRESACCTTO() {
        return presacctto;
    }

    /**
     * Sets the value of the presacctto property.
     * 
     * @param value
     *     allowed object is
     *     {@link PresentmentAccount }
     *     
     */
    public void setPRESACCTTO(PresentmentAccount value) {
        this.presacctto = value;
    }

}
