//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "SONRQ" is of type "SignonRequest"
 *       
 * 
 * <p>Java class for SignonRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignonRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DTCLIENT" type="{http://ofx.net/types/2003/04}DateTimeType"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="USERID" type="{http://ofx.net/types/2003/04}IdType"/>
 *             &lt;element name="USERPASS" type="{http://ofx.net/types/2003/04}PasswordType"/>
 *           &lt;/sequence>
 *           &lt;element name="USERKEY" type="{http://ofx.net/types/2003/04}UserKeyType"/>
 *         &lt;/choice>
 *         &lt;element name="GENUSERKEY" type="{http://ofx.net/types/2003/04}BooleanType" minOccurs="0"/>
 *         &lt;element name="LANGUAGE" type="{http://ofx.net/types/2003/04}LanguageEnum"/>
 *         &lt;element name="FI" type="{http://ofx.net/types/2003/04}FinancialInstitution" minOccurs="0"/>
 *         &lt;element name="SESSCOOKIE" type="{http://ofx.net/types/2003/04}SessionCookieType" minOccurs="0"/>
 *         &lt;element name="APPID" type="{http://ofx.net/types/2003/04}ApplicationIdType"/>
 *         &lt;element name="APPVER" type="{http://ofx.net/types/2003/04}IntegerType"/>
 *         &lt;element name="CLIENTUID" type="{http://ofx.net/types/2003/04}ClientUidType" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="USERCRED1" type="{http://ofx.net/types/2003/04}UserCredType"/>
 *           &lt;element name="USERCRED2" type="{http://ofx.net/types/2003/04}UserCredType" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element name="AUTHTOKEN" type="{http://ofx.net/types/2003/04}AuthTokenType" minOccurs="0"/>
 *         &lt;element name="ACCESSKEY" type="{http://ofx.net/types/2003/04}AccessKeyType" minOccurs="0"/>
 *         &lt;element name="MFACHALLENGEANSWER" type="{http://ofx.net/types/2003/04}MFAChallengeAnswer" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignonRequest", propOrder = {
    "dtclient",
    "userid",
    "userpass",
    "userkey",
    "genuserkey",
    "language",
    "fi",
    "sesscookie",
    "appid",
    "appver",
    "clientuid",
    "usercred1",
    "usercred2",
    "authtoken",
    "accesskey",
    "mfachallengeanswer"
})
public class SignonRequest {

    @XmlElement(name = "DTCLIENT", required = true)
    protected String dtclient;
    @XmlElement(name = "USERID")
    protected String userid;
    @XmlElement(name = "USERPASS")
    protected String userpass;
    @XmlElement(name = "USERKEY")
    protected String userkey;
    @XmlElement(name = "GENUSERKEY")
    protected BooleanType genuserkey;
    @XmlElement(name = "LANGUAGE", required = true)
    protected LanguageEnum language;
    @XmlElement(name = "FI")
    protected FinancialInstitution fi;
    @XmlElement(name = "SESSCOOKIE")
    protected String sesscookie;
    @XmlElement(name = "APPID", required = true)
    protected String appid;
    @XmlElement(name = "APPVER", required = true)
    protected String appver;
    @XmlElement(name = "CLIENTUID")
    protected String clientuid;
    @XmlElement(name = "USERCRED1")
    protected String usercred1;
    @XmlElement(name = "USERCRED2")
    protected String usercred2;
    @XmlElement(name = "AUTHTOKEN")
    protected String authtoken;
    @XmlElement(name = "ACCESSKEY")
    protected String accesskey;
    @XmlElement(name = "MFACHALLENGEANSWER")
    protected List<MFAChallengeAnswer> mfachallengeanswer;

    /**
     * Gets the value of the dtclient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTCLIENT() {
        return dtclient;
    }

    /**
     * Sets the value of the dtclient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTCLIENT(String value) {
        this.dtclient = value;
    }

    /**
     * Gets the value of the userid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERID() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERID(String value) {
        this.userid = value;
    }

    /**
     * Gets the value of the userpass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERPASS() {
        return userpass;
    }

    /**
     * Sets the value of the userpass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERPASS(String value) {
        this.userpass = value;
    }

    /**
     * Gets the value of the userkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERKEY() {
        return userkey;
    }

    /**
     * Sets the value of the userkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERKEY(String value) {
        this.userkey = value;
    }

    /**
     * Gets the value of the genuserkey property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getGENUSERKEY() {
        return genuserkey;
    }

    /**
     * Sets the value of the genuserkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setGENUSERKEY(BooleanType value) {
        this.genuserkey = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageEnum }
     *     
     */
    public LanguageEnum getLANGUAGE() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageEnum }
     *     
     */
    public void setLANGUAGE(LanguageEnum value) {
        this.language = value;
    }

    /**
     * Gets the value of the fi property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialInstitution }
     *     
     */
    public FinancialInstitution getFI() {
        return fi;
    }

    /**
     * Sets the value of the fi property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialInstitution }
     *     
     */
    public void setFI(FinancialInstitution value) {
        this.fi = value;
    }

    /**
     * Gets the value of the sesscookie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSESSCOOKIE() {
        return sesscookie;
    }

    /**
     * Sets the value of the sesscookie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSESSCOOKIE(String value) {
        this.sesscookie = value;
    }

    /**
     * Gets the value of the appid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPID() {
        return appid;
    }

    /**
     * Sets the value of the appid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPID(String value) {
        this.appid = value;
    }

    /**
     * Gets the value of the appver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPVER() {
        return appver;
    }

    /**
     * Sets the value of the appver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPVER(String value) {
        this.appver = value;
    }

    /**
     * Gets the value of the clientuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLIENTUID() {
        return clientuid;
    }

    /**
     * Sets the value of the clientuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLIENTUID(String value) {
        this.clientuid = value;
    }

    /**
     * Gets the value of the usercred1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERCRED1() {
        return usercred1;
    }

    /**
     * Sets the value of the usercred1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERCRED1(String value) {
        this.usercred1 = value;
    }

    /**
     * Gets the value of the usercred2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERCRED2() {
        return usercred2;
    }

    /**
     * Sets the value of the usercred2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERCRED2(String value) {
        this.usercred2 = value;
    }

    /**
     * Gets the value of the authtoken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUTHTOKEN() {
        return authtoken;
    }

    /**
     * Sets the value of the authtoken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUTHTOKEN(String value) {
        this.authtoken = value;
    }

    /**
     * Gets the value of the accesskey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCESSKEY() {
        return accesskey;
    }

    /**
     * Sets the value of the accesskey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCESSKEY(String value) {
        this.accesskey = value;
    }

    /**
     * Gets the value of the mfachallengeanswer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mfachallengeanswer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMFACHALLENGEANSWER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MFAChallengeAnswer }
     * 
     * 
     */
    public List<MFAChallengeAnswer> getMFACHALLENGEANSWER() {
        if (mfachallengeanswer == null) {
            mfachallengeanswer = new ArrayList<MFAChallengeAnswer>();
        }
        return this.mfachallengeanswer;
    }

}
