//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "SIGNONINFO" is of type "SignonInfo"
 *       
 * 
 * <p>Java class for SignonInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignonInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SIGNONREALM" type="{http://ofx.net/types/2003/04}GenericNameType"/>
 *         &lt;element name="MIN" type="{http://ofx.net/types/2003/04}MAXMINType"/>
 *         &lt;element name="MAX" type="{http://ofx.net/types/2003/04}MAXMINType"/>
 *         &lt;element name="CHARTYPE" type="{http://ofx.net/types/2003/04}CharTypeEnum"/>
 *         &lt;element name="CASESEN" type="{http://ofx.net/types/2003/04}BooleanType"/>
 *         &lt;element name="SPECIAL" type="{http://ofx.net/types/2003/04}BooleanType"/>
 *         &lt;element name="SPACES" type="{http://ofx.net/types/2003/04}BooleanType"/>
 *         &lt;element name="PINCH" type="{http://ofx.net/types/2003/04}BooleanType"/>
 *         &lt;element name="CHGPINFIRST" type="{http://ofx.net/types/2003/04}BooleanType"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="USERCRED1LABEL" type="{http://ofx.net/types/2003/04}MFATextType"/>
 *           &lt;element name="USERCRED2LABEL" type="{http://ofx.net/types/2003/04}MFATextType" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element name="CLIENTUIDREQ" type="{http://ofx.net/types/2003/04}BooleanType" minOccurs="0"/>
 *         &lt;element name="AUTHTOKENFIRST" type="{http://ofx.net/types/2003/04}BooleanType" minOccurs="0"/>
 *         &lt;element name="AUTHTOKENLABEL" type="{http://ofx.net/types/2003/04}MFATextType" minOccurs="0"/>
 *         &lt;element name="AUTHTOKENINFOURL" type="{http://ofx.net/types/2003/04}MFAUrlType" minOccurs="0"/>
 *         &lt;element name="MFACHALLENGESUPT" type="{http://ofx.net/types/2003/04}BooleanType" minOccurs="0"/>
 *         &lt;element name="MFACHALLENGEFIRST" type="{http://ofx.net/types/2003/04}BooleanType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignonInfo", propOrder = {
    "signonrealm",
    "min",
    "max",
    "chartype",
    "casesen",
    "special",
    "spaces",
    "pinch",
    "chgpinfirst",
    "usercred1LABEL",
    "usercred2LABEL",
    "clientuidreq",
    "authtokenfirst",
    "authtokenlabel",
    "authtokeninfourl",
    "mfachallengesupt",
    "mfachallengefirst"
})
public class SignonInfo {

    @XmlElement(name = "SIGNONREALM", required = true)
    protected String signonrealm;
    @XmlElement(name = "MIN", required = true)
    protected String min;
    @XmlElement(name = "MAX", required = true)
    protected String max;
    @XmlElement(name = "CHARTYPE", required = true)
    protected CharTypeEnum chartype;
    @XmlElement(name = "CASESEN", required = true)
    protected BooleanType casesen;
    @XmlElement(name = "SPECIAL", required = true)
    protected BooleanType special;
    @XmlElement(name = "SPACES", required = true)
    protected BooleanType spaces;
    @XmlElement(name = "PINCH", required = true)
    protected BooleanType pinch;
    @XmlElement(name = "CHGPINFIRST", required = true)
    protected BooleanType chgpinfirst;
    @XmlElement(name = "USERCRED1LABEL")
    protected String usercred1LABEL;
    @XmlElement(name = "USERCRED2LABEL")
    protected String usercred2LABEL;
    @XmlElement(name = "CLIENTUIDREQ")
    protected BooleanType clientuidreq;
    @XmlElement(name = "AUTHTOKENFIRST")
    protected BooleanType authtokenfirst;
    @XmlElement(name = "AUTHTOKENLABEL")
    protected String authtokenlabel;
    @XmlElement(name = "AUTHTOKENINFOURL")
    protected String authtokeninfourl;
    @XmlElement(name = "MFACHALLENGESUPT")
    protected BooleanType mfachallengesupt;
    @XmlElement(name = "MFACHALLENGEFIRST")
    protected BooleanType mfachallengefirst;

    /**
     * Gets the value of the signonrealm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIGNONREALM() {
        return signonrealm;
    }

    /**
     * Sets the value of the signonrealm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIGNONREALM(String value) {
        this.signonrealm = value;
    }

    /**
     * Gets the value of the min property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMIN() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMIN(String value) {
        this.min = value;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAX() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAX(String value) {
        this.max = value;
    }

    /**
     * Gets the value of the chartype property.
     * 
     * @return
     *     possible object is
     *     {@link CharTypeEnum }
     *     
     */
    public CharTypeEnum getCHARTYPE() {
        return chartype;
    }

    /**
     * Sets the value of the chartype property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharTypeEnum }
     *     
     */
    public void setCHARTYPE(CharTypeEnum value) {
        this.chartype = value;
    }

    /**
     * Gets the value of the casesen property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getCASESEN() {
        return casesen;
    }

    /**
     * Sets the value of the casesen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setCASESEN(BooleanType value) {
        this.casesen = value;
    }

    /**
     * Gets the value of the special property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getSPECIAL() {
        return special;
    }

    /**
     * Sets the value of the special property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setSPECIAL(BooleanType value) {
        this.special = value;
    }

    /**
     * Gets the value of the spaces property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getSPACES() {
        return spaces;
    }

    /**
     * Sets the value of the spaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setSPACES(BooleanType value) {
        this.spaces = value;
    }

    /**
     * Gets the value of the pinch property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getPINCH() {
        return pinch;
    }

    /**
     * Sets the value of the pinch property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setPINCH(BooleanType value) {
        this.pinch = value;
    }

    /**
     * Gets the value of the chgpinfirst property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getCHGPINFIRST() {
        return chgpinfirst;
    }

    /**
     * Sets the value of the chgpinfirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setCHGPINFIRST(BooleanType value) {
        this.chgpinfirst = value;
    }

    /**
     * Gets the value of the usercred1LABEL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERCRED1LABEL() {
        return usercred1LABEL;
    }

    /**
     * Sets the value of the usercred1LABEL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERCRED1LABEL(String value) {
        this.usercred1LABEL = value;
    }

    /**
     * Gets the value of the usercred2LABEL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERCRED2LABEL() {
        return usercred2LABEL;
    }

    /**
     * Sets the value of the usercred2LABEL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERCRED2LABEL(String value) {
        this.usercred2LABEL = value;
    }

    /**
     * Gets the value of the clientuidreq property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getCLIENTUIDREQ() {
        return clientuidreq;
    }

    /**
     * Sets the value of the clientuidreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setCLIENTUIDREQ(BooleanType value) {
        this.clientuidreq = value;
    }

    /**
     * Gets the value of the authtokenfirst property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getAUTHTOKENFIRST() {
        return authtokenfirst;
    }

    /**
     * Sets the value of the authtokenfirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setAUTHTOKENFIRST(BooleanType value) {
        this.authtokenfirst = value;
    }

    /**
     * Gets the value of the authtokenlabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUTHTOKENLABEL() {
        return authtokenlabel;
    }

    /**
     * Sets the value of the authtokenlabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUTHTOKENLABEL(String value) {
        this.authtokenlabel = value;
    }

    /**
     * Gets the value of the authtokeninfourl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUTHTOKENINFOURL() {
        return authtokeninfourl;
    }

    /**
     * Sets the value of the authtokeninfourl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUTHTOKENINFOURL(String value) {
        this.authtokeninfourl = value;
    }

    /**
     * Gets the value of the mfachallengesupt property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getMFACHALLENGESUPT() {
        return mfachallengesupt;
    }

    /**
     * Sets the value of the mfachallengesupt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setMFACHALLENGESUPT(BooleanType value) {
        this.mfachallengesupt = value;
    }

    /**
     * Gets the value of the mfachallengefirst property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getMFACHALLENGEFIRST() {
        return mfachallengefirst;
    }

    /**
     * Sets the value of the mfachallengefirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setMFACHALLENGEFIRST(BooleanType value) {
        this.mfachallengefirst = value;
    }

}
