//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "SIGNUPMSGSRQV1" is of type "SignupRequestMessageSetV1"
 *       
 * 
 * <p>Java class for SignupRequestMessageSetV1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignupRequestMessageSetV1">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractRequestMessageSet">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="ENROLLTRNRQ" type="{http://ofx.net/types/2003/04}EnrollTransactionRequest"/>
 *         &lt;element name="ACCTINFOTRNRQ" type="{http://ofx.net/types/2003/04}AccountInfoTransactionRequest"/>
 *         &lt;element name="CHGUSERINFOTRNRQ" type="{http://ofx.net/types/2003/04}ChangeUserInfoTransactionRequest"/>
 *         &lt;element name="CHGUSERINFOSYNCRQ" type="{http://ofx.net/types/2003/04}ChangeUserInfoSyncRequest"/>
 *         &lt;element name="ACCTTRNRQ" type="{http://ofx.net/types/2003/04}AccountTransactionRequest"/>
 *         &lt;element name="ACCTSYNCRQ" type="{http://ofx.net/types/2003/04}AccountSyncRequest"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignupRequestMessageSetV1", propOrder = {
    "enrolltrnrqOrACCTINFOTRNRQOrCHGUSERINFOTRNRQ"
})
public class SignupRequestMessageSetV1
    extends AbstractRequestMessageSet
{

    @XmlElements({
        @XmlElement(name = "ENROLLTRNRQ", type = EnrollTransactionRequest.class),
        @XmlElement(name = "ACCTINFOTRNRQ", type = AccountInfoTransactionRequest.class),
        @XmlElement(name = "CHGUSERINFOTRNRQ", type = ChangeUserInfoTransactionRequest.class),
        @XmlElement(name = "CHGUSERINFOSYNCRQ", type = ChangeUserInfoSyncRequest.class),
        @XmlElement(name = "ACCTTRNRQ", type = AccountTransactionRequest.class),
        @XmlElement(name = "ACCTSYNCRQ", type = AccountSyncRequest.class)
    })
    protected List<AbstractRequest> enrolltrnrqOrACCTINFOTRNRQOrCHGUSERINFOTRNRQ;

    /**
     * Gets the value of the enrolltrnrqOrACCTINFOTRNRQOrCHGUSERINFOTRNRQ property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enrolltrnrqOrACCTINFOTRNRQOrCHGUSERINFOTRNRQ property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getENROLLTRNRQOrACCTINFOTRNRQOrCHGUSERINFOTRNRQ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnrollTransactionRequest }
     * {@link AccountInfoTransactionRequest }
     * {@link ChangeUserInfoTransactionRequest }
     * {@link ChangeUserInfoSyncRequest }
     * {@link AccountTransactionRequest }
     * {@link AccountSyncRequest }
     * 
     * 
     */
    public List<AbstractRequest> getENROLLTRNRQOrACCTINFOTRNRQOrCHGUSERINFOTRNRQ() {
        if (enrolltrnrqOrACCTINFOTRNRQOrCHGUSERINFOTRNRQ == null) {
            enrolltrnrqOrACCTINFOTRNRQOrCHGUSERINFOTRNRQ = new ArrayList<AbstractRequest>();
        }
        return this.enrolltrnrqOrACCTINFOTRNRQOrCHGUSERINFOTRNRQ;
    }

}
