//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "STMTENDTRNRQ" is of type "StatementEndTransactionRequest"
 *       
 * 
 * <p>Java class for StatementEndTransactionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatementEndTransactionRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractTransactionRequest">
 *       &lt;sequence>
 *         &lt;element name="STMTENDRQ" type="{http://ofx.net/types/2003/04}StatementEndRequest"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatementEndTransactionRequest", propOrder = {
    "stmtendrq"
})
public class StatementEndTransactionRequest
    extends AbstractTransactionRequest
{

    @XmlElement(name = "STMTENDRQ", required = true)
    protected StatementEndRequest stmtendrq;

    /**
     * Gets the value of the stmtendrq property.
     * 
     * @return
     *     possible object is
     *     {@link StatementEndRequest }
     *     
     */
    public StatementEndRequest getSTMTENDRQ() {
        return stmtendrq;
    }

    /**
     * Sets the value of the stmtendrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatementEndRequest }
     *     
     */
    public void setSTMTENDRQ(StatementEndRequest value) {
        this.stmtendrq = value;
    }

}
