//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "STPCHKNUM" is of type "StopCheckNumber"
 *       
 * 
 * <p>Java class for StopCheckNumber complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StopCheckNumber">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CHECKNUM" type="{http://ofx.net/types/2003/04}CheckNumberType"/>
 *         &lt;element name="NAME" type="{http://ofx.net/types/2003/04}GenericNameType" minOccurs="0"/>
 *         &lt;element name="DTUSER" type="{http://ofx.net/types/2003/04}DateTimeType" minOccurs="0"/>
 *         &lt;element name="TRNAMT" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="CHKSTATUS" type="{http://ofx.net/types/2003/04}CheckStatusEnum"/>
 *         &lt;element name="CHKERROR" type="{http://ofx.net/types/2003/04}MessageType" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="CURRENCY" type="{http://ofx.net/types/2003/04}Currency"/>
 *           &lt;element name="ORIGCURRENCY" type="{http://ofx.net/types/2003/04}Currency"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StopCheckNumber", propOrder = {
    "checknum",
    "name",
    "dtuser",
    "trnamt",
    "chkstatus",
    "chkerror",
    "currency",
    "origcurrency"
})
public class StopCheckNumber {

    @XmlElement(name = "CHECKNUM", required = true)
    protected String checknum;
    @XmlElement(name = "NAME")
    protected String name;
    @XmlElement(name = "DTUSER")
    protected String dtuser;
    @XmlElement(name = "TRNAMT")
    protected String trnamt;
    @XmlElement(name = "CHKSTATUS", required = true)
    protected String chkstatus;
    @XmlElement(name = "CHKERROR")
    protected String chkerror;
    @XmlElement(name = "CURRENCY")
    protected Currency currency;
    @XmlElement(name = "ORIGCURRENCY")
    protected Currency origcurrency;

    /**
     * Gets the value of the checknum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHECKNUM() {
        return checknum;
    }

    /**
     * Sets the value of the checknum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHECKNUM(String value) {
        this.checknum = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dtuser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTUSER() {
        return dtuser;
    }

    /**
     * Sets the value of the dtuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTUSER(String value) {
        this.dtuser = value;
    }

    /**
     * Gets the value of the trnamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRNAMT() {
        return trnamt;
    }

    /**
     * Sets the value of the trnamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRNAMT(String value) {
        this.trnamt = value;
    }

    /**
     * Gets the value of the chkstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHKSTATUS() {
        return chkstatus;
    }

    /**
     * Sets the value of the chkstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHKSTATUS(String value) {
        this.chkstatus = value;
    }

    /**
     * Gets the value of the chkerror property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHKERROR() {
        return chkerror;
    }

    /**
     * Sets the value of the chkerror property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHKERROR(String value) {
        this.chkerror = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getCURRENCY() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setCURRENCY(Currency value) {
        this.currency = value;
    }

    /**
     * Gets the value of the origcurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getORIGCURRENCY() {
        return origcurrency;
    }

    /**
     * Sets the value of the origcurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setORIGCURRENCY(Currency value) {
        this.origcurrency = value;
    }

}
