//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "TAX1099DIV_V100" is of type "Tax1099DIV_V100"
 *       
 * 
 * <p>Java class for Tax1099DIV_V100 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tax1099DIV_V100">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractTaxForm1099">
 *       &lt;sequence>
 *         &lt;element name="ORDDIV" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="QUALIFIEDDIV" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="TOTCAPGAIN" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="POSTMAY5CAPGAIN" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="P28GAIN" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="UNRECSEC1250" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="SEC1202" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="QUAL5YEAR" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="NONTAXDIST" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="FEDTAXWH" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="INVESTEXP" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="FORTAXPD" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="FORCNT" type="{http://ofx.net/types/2003/04}GenericNameType" minOccurs="0"/>
 *         &lt;element name="CASHLIQ" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="NONCASHLIQ" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="PAYERADDR" type="{http://ofx.net/types/2003/04}PayerAddress"/>
 *         &lt;element name="PAYERID" type="{http://ofx.net/types/2003/04}GenericNameType"/>
 *         &lt;element name="RECADDR" type="{http://ofx.net/types/2003/04}RecurringAddress" minOccurs="0"/>
 *         &lt;element name="RECID" type="{http://ofx.net/types/2003/04}IdType"/>
 *         &lt;element name="RECACCT" type="{http://ofx.net/types/2003/04}GenericNameType" minOccurs="0"/>
 *         &lt;element name="TINNOT" type="{http://ofx.net/types/2003/04}BooleanType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tax1099DIV_V100", propOrder = {
    "orddiv",
    "qualifieddiv",
    "totcapgain",
    "postmay5CAPGAIN",
    "p28GAIN",
    "unrecsec1250",
    "sec1202",
    "qual5YEAR",
    "nontaxdist",
    "fedtaxwh",
    "investexp",
    "fortaxpd",
    "forcnt",
    "cashliq",
    "noncashliq",
    "payeraddr",
    "payerid",
    "recaddr",
    "recid",
    "recacct",
    "tinnot"
})
public class Tax1099DIVV100
    extends AbstractTaxForm1099
{

    @XmlElement(name = "ORDDIV")
    protected String orddiv;
    @XmlElement(name = "QUALIFIEDDIV")
    protected String qualifieddiv;
    @XmlElement(name = "TOTCAPGAIN")
    protected String totcapgain;
    @XmlElement(name = "POSTMAY5CAPGAIN")
    protected String postmay5CAPGAIN;
    @XmlElement(name = "P28GAIN")
    protected String p28GAIN;
    @XmlElement(name = "UNRECSEC1250")
    protected String unrecsec1250;
    @XmlElement(name = "SEC1202")
    protected String sec1202;
    @XmlElement(name = "QUAL5YEAR")
    protected String qual5YEAR;
    @XmlElement(name = "NONTAXDIST")
    protected String nontaxdist;
    @XmlElement(name = "FEDTAXWH")
    protected String fedtaxwh;
    @XmlElement(name = "INVESTEXP")
    protected String investexp;
    @XmlElement(name = "FORTAXPD")
    protected String fortaxpd;
    @XmlElement(name = "FORCNT")
    protected String forcnt;
    @XmlElement(name = "CASHLIQ")
    protected String cashliq;
    @XmlElement(name = "NONCASHLIQ")
    protected String noncashliq;
    @XmlElement(name = "PAYERADDR", required = true)
    protected PayerAddress payeraddr;
    @XmlElement(name = "PAYERID", required = true)
    protected String payerid;
    @XmlElement(name = "RECADDR")
    protected RecurringAddress recaddr;
    @XmlElement(name = "RECID", required = true)
    protected String recid;
    @XmlElement(name = "RECACCT")
    protected String recacct;
    @XmlElement(name = "TINNOT")
    protected BooleanType tinnot;

    /**
     * Gets the value of the orddiv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDDIV() {
        return orddiv;
    }

    /**
     * Sets the value of the orddiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDDIV(String value) {
        this.orddiv = value;
    }

    /**
     * Gets the value of the qualifieddiv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQUALIFIEDDIV() {
        return qualifieddiv;
    }

    /**
     * Sets the value of the qualifieddiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQUALIFIEDDIV(String value) {
        this.qualifieddiv = value;
    }

    /**
     * Gets the value of the totcapgain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTCAPGAIN() {
        return totcapgain;
    }

    /**
     * Sets the value of the totcapgain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTCAPGAIN(String value) {
        this.totcapgain = value;
    }

    /**
     * Gets the value of the postmay5CAPGAIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSTMAY5CAPGAIN() {
        return postmay5CAPGAIN;
    }

    /**
     * Sets the value of the postmay5CAPGAIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSTMAY5CAPGAIN(String value) {
        this.postmay5CAPGAIN = value;
    }

    /**
     * Gets the value of the p28GAIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getP28GAIN() {
        return p28GAIN;
    }

    /**
     * Sets the value of the p28GAIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setP28GAIN(String value) {
        this.p28GAIN = value;
    }

    /**
     * Gets the value of the unrecsec1250 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNRECSEC1250() {
        return unrecsec1250;
    }

    /**
     * Sets the value of the unrecsec1250 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNRECSEC1250(String value) {
        this.unrecsec1250 = value;
    }

    /**
     * Gets the value of the sec1202 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEC1202() {
        return sec1202;
    }

    /**
     * Sets the value of the sec1202 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEC1202(String value) {
        this.sec1202 = value;
    }

    /**
     * Gets the value of the qual5YEAR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQUAL5YEAR() {
        return qual5YEAR;
    }

    /**
     * Sets the value of the qual5YEAR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQUAL5YEAR(String value) {
        this.qual5YEAR = value;
    }

    /**
     * Gets the value of the nontaxdist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNONTAXDIST() {
        return nontaxdist;
    }

    /**
     * Sets the value of the nontaxdist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNONTAXDIST(String value) {
        this.nontaxdist = value;
    }

    /**
     * Gets the value of the fedtaxwh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFEDTAXWH() {
        return fedtaxwh;
    }

    /**
     * Sets the value of the fedtaxwh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFEDTAXWH(String value) {
        this.fedtaxwh = value;
    }

    /**
     * Gets the value of the investexp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVESTEXP() {
        return investexp;
    }

    /**
     * Sets the value of the investexp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVESTEXP(String value) {
        this.investexp = value;
    }

    /**
     * Gets the value of the fortaxpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFORTAXPD() {
        return fortaxpd;
    }

    /**
     * Sets the value of the fortaxpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFORTAXPD(String value) {
        this.fortaxpd = value;
    }

    /**
     * Gets the value of the forcnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFORCNT() {
        return forcnt;
    }

    /**
     * Sets the value of the forcnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFORCNT(String value) {
        this.forcnt = value;
    }

    /**
     * Gets the value of the cashliq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCASHLIQ() {
        return cashliq;
    }

    /**
     * Sets the value of the cashliq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCASHLIQ(String value) {
        this.cashliq = value;
    }

    /**
     * Gets the value of the noncashliq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNONCASHLIQ() {
        return noncashliq;
    }

    /**
     * Sets the value of the noncashliq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNONCASHLIQ(String value) {
        this.noncashliq = value;
    }

    /**
     * Gets the value of the payeraddr property.
     * 
     * @return
     *     possible object is
     *     {@link PayerAddress }
     *     
     */
    public PayerAddress getPAYERADDR() {
        return payeraddr;
    }

    /**
     * Sets the value of the payeraddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerAddress }
     *     
     */
    public void setPAYERADDR(PayerAddress value) {
        this.payeraddr = value;
    }

    /**
     * Gets the value of the payerid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYERID() {
        return payerid;
    }

    /**
     * Sets the value of the payerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYERID(String value) {
        this.payerid = value;
    }

    /**
     * Gets the value of the recaddr property.
     * 
     * @return
     *     possible object is
     *     {@link RecurringAddress }
     *     
     */
    public RecurringAddress getRECADDR() {
        return recaddr;
    }

    /**
     * Sets the value of the recaddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecurringAddress }
     *     
     */
    public void setRECADDR(RecurringAddress value) {
        this.recaddr = value;
    }

    /**
     * Gets the value of the recid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECID() {
        return recid;
    }

    /**
     * Sets the value of the recid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECID(String value) {
        this.recid = value;
    }

    /**
     * Gets the value of the recacct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECACCT() {
        return recacct;
    }

    /**
     * Sets the value of the recacct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECACCT(String value) {
        this.recacct = value;
    }

    /**
     * Gets the value of the tinnot property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getTINNOT() {
        return tinnot;
    }

    /**
     * Sets the value of the tinnot property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setTINNOT(BooleanType value) {
        this.tinnot = value;
    }

}
