//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "TAX1099MISC_V100" is of type "Tax1099Misc_V100"
 *       
 * 
 * <p>Java class for Tax1099MISC_V100 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tax1099MISC_V100">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractTaxForm1099">
 *       &lt;sequence>
 *         &lt;element name="RENTS" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="ROYALTIES" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="OTHERINCOME" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="FEDTAXWH" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="FISHBOATPRO" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="MEDHEALTHPAY" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="NONEMPCOMP" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="SUBPMTS" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="PAYER5KSALES" type="{http://ofx.net/types/2003/04}BooleanType" minOccurs="0"/>
 *         &lt;element name="CROPINSPRO" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="STTAXWH" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *             &lt;element name="PAYERSTATE" type="{http://ofx.net/types/2003/04}StateCodeType" minOccurs="0"/>
 *             &lt;element name="PAYERSTID" type="{http://ofx.net/types/2003/04}IdType" minOccurs="0"/>
 *             &lt;element name="STINCOME" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element name="ADDLSTTAXWHAGG" type="{http://ofx.net/types/2003/04}AdditionalStateTaxWithheldAggregate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="GROSSATTOR" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="EXCSGLDN" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="SEC409ADEFERRALS" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="SEC409AINCOME" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="PAYERADDR" type="{http://ofx.net/types/2003/04}PayerAddress"/>
 *         &lt;element name="PAYERID" type="{http://ofx.net/types/2003/04}GenericNameType"/>
 *         &lt;element name="RECADDR" type="{http://ofx.net/types/2003/04}RecurringAddress" minOccurs="0"/>
 *         &lt;element name="RECID" type="{http://ofx.net/types/2003/04}IdType"/>
 *         &lt;element name="RECACCT" type="{http://ofx.net/types/2003/04}GenericNameType" minOccurs="0"/>
 *         &lt;element name="TINNOT" type="{http://ofx.net/types/2003/04}BooleanType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tax1099MISC_V100", propOrder = {
    "rents",
    "royalties",
    "otherincome",
    "fedtaxwh",
    "fishboatpro",
    "medhealthpay",
    "nonempcomp",
    "subpmts",
    "payer5KSALES",
    "cropinspro",
    "sttaxwh",
    "payerstate",
    "payerstid",
    "stincome",
    "addlsttaxwhagg",
    "grossattor",
    "excsgldn",
    "sec409ADEFERRALS",
    "sec409AINCOME",
    "payeraddr",
    "payerid",
    "recaddr",
    "recid",
    "recacct",
    "tinnot"
})
public class Tax1099MISCV100
    extends AbstractTaxForm1099
{

    @XmlElement(name = "RENTS")
    protected String rents;
    @XmlElement(name = "ROYALTIES")
    protected String royalties;
    @XmlElement(name = "OTHERINCOME")
    protected String otherincome;
    @XmlElement(name = "FEDTAXWH")
    protected String fedtaxwh;
    @XmlElement(name = "FISHBOATPRO")
    protected String fishboatpro;
    @XmlElement(name = "MEDHEALTHPAY")
    protected String medhealthpay;
    @XmlElement(name = "NONEMPCOMP")
    protected String nonempcomp;
    @XmlElement(name = "SUBPMTS")
    protected String subpmts;
    @XmlElement(name = "PAYER5KSALES")
    protected BooleanType payer5KSALES;
    @XmlElement(name = "CROPINSPRO")
    protected String cropinspro;
    @XmlElement(name = "STTAXWH")
    protected String sttaxwh;
    @XmlElement(name = "PAYERSTATE")
    protected String payerstate;
    @XmlElement(name = "PAYERSTID")
    protected String payerstid;
    @XmlElement(name = "STINCOME")
    protected String stincome;
    @XmlElement(name = "ADDLSTTAXWHAGG")
    protected List<AdditionalStateTaxWithheldAggregate> addlsttaxwhagg;
    @XmlElement(name = "GROSSATTOR")
    protected String grossattor;
    @XmlElement(name = "EXCSGLDN")
    protected String excsgldn;
    @XmlElement(name = "SEC409ADEFERRALS")
    protected String sec409ADEFERRALS;
    @XmlElement(name = "SEC409AINCOME")
    protected String sec409AINCOME;
    @XmlElement(name = "PAYERADDR", required = true)
    protected PayerAddress payeraddr;
    @XmlElement(name = "PAYERID", required = true)
    protected String payerid;
    @XmlElement(name = "RECADDR")
    protected RecurringAddress recaddr;
    @XmlElement(name = "RECID", required = true)
    protected String recid;
    @XmlElement(name = "RECACCT")
    protected String recacct;
    @XmlElement(name = "TINNOT")
    protected BooleanType tinnot;

    /**
     * Gets the value of the rents property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRENTS() {
        return rents;
    }

    /**
     * Sets the value of the rents property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRENTS(String value) {
        this.rents = value;
    }

    /**
     * Gets the value of the royalties property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getROYALTIES() {
        return royalties;
    }

    /**
     * Sets the value of the royalties property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setROYALTIES(String value) {
        this.royalties = value;
    }

    /**
     * Gets the value of the otherincome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOTHERINCOME() {
        return otherincome;
    }

    /**
     * Sets the value of the otherincome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOTHERINCOME(String value) {
        this.otherincome = value;
    }

    /**
     * Gets the value of the fedtaxwh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFEDTAXWH() {
        return fedtaxwh;
    }

    /**
     * Sets the value of the fedtaxwh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFEDTAXWH(String value) {
        this.fedtaxwh = value;
    }

    /**
     * Gets the value of the fishboatpro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFISHBOATPRO() {
        return fishboatpro;
    }

    /**
     * Sets the value of the fishboatpro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFISHBOATPRO(String value) {
        this.fishboatpro = value;
    }

    /**
     * Gets the value of the medhealthpay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEDHEALTHPAY() {
        return medhealthpay;
    }

    /**
     * Sets the value of the medhealthpay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEDHEALTHPAY(String value) {
        this.medhealthpay = value;
    }

    /**
     * Gets the value of the nonempcomp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNONEMPCOMP() {
        return nonempcomp;
    }

    /**
     * Sets the value of the nonempcomp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNONEMPCOMP(String value) {
        this.nonempcomp = value;
    }

    /**
     * Gets the value of the subpmts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBPMTS() {
        return subpmts;
    }

    /**
     * Sets the value of the subpmts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBPMTS(String value) {
        this.subpmts = value;
    }

    /**
     * Gets the value of the payer5KSALES property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getPAYER5KSALES() {
        return payer5KSALES;
    }

    /**
     * Sets the value of the payer5KSALES property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setPAYER5KSALES(BooleanType value) {
        this.payer5KSALES = value;
    }

    /**
     * Gets the value of the cropinspro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCROPINSPRO() {
        return cropinspro;
    }

    /**
     * Sets the value of the cropinspro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCROPINSPRO(String value) {
        this.cropinspro = value;
    }

    /**
     * Gets the value of the sttaxwh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTTAXWH() {
        return sttaxwh;
    }

    /**
     * Sets the value of the sttaxwh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTTAXWH(String value) {
        this.sttaxwh = value;
    }

    /**
     * Gets the value of the payerstate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYERSTATE() {
        return payerstate;
    }

    /**
     * Sets the value of the payerstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYERSTATE(String value) {
        this.payerstate = value;
    }

    /**
     * Gets the value of the payerstid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYERSTID() {
        return payerstid;
    }

    /**
     * Sets the value of the payerstid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYERSTID(String value) {
        this.payerstid = value;
    }

    /**
     * Gets the value of the stincome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTINCOME() {
        return stincome;
    }

    /**
     * Sets the value of the stincome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTINCOME(String value) {
        this.stincome = value;
    }

    /**
     * Gets the value of the addlsttaxwhagg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addlsttaxwhagg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getADDLSTTAXWHAGG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalStateTaxWithheldAggregate }
     * 
     * 
     */
    public List<AdditionalStateTaxWithheldAggregate> getADDLSTTAXWHAGG() {
        if (addlsttaxwhagg == null) {
            addlsttaxwhagg = new ArrayList<AdditionalStateTaxWithheldAggregate>();
        }
        return this.addlsttaxwhagg;
    }

    /**
     * Gets the value of the grossattor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGROSSATTOR() {
        return grossattor;
    }

    /**
     * Sets the value of the grossattor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGROSSATTOR(String value) {
        this.grossattor = value;
    }

    /**
     * Gets the value of the excsgldn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXCSGLDN() {
        return excsgldn;
    }

    /**
     * Sets the value of the excsgldn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXCSGLDN(String value) {
        this.excsgldn = value;
    }

    /**
     * Gets the value of the sec409ADEFERRALS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEC409ADEFERRALS() {
        return sec409ADEFERRALS;
    }

    /**
     * Sets the value of the sec409ADEFERRALS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEC409ADEFERRALS(String value) {
        this.sec409ADEFERRALS = value;
    }

    /**
     * Gets the value of the sec409AINCOME property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEC409AINCOME() {
        return sec409AINCOME;
    }

    /**
     * Sets the value of the sec409AINCOME property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEC409AINCOME(String value) {
        this.sec409AINCOME = value;
    }

    /**
     * Gets the value of the payeraddr property.
     * 
     * @return
     *     possible object is
     *     {@link PayerAddress }
     *     
     */
    public PayerAddress getPAYERADDR() {
        return payeraddr;
    }

    /**
     * Sets the value of the payeraddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerAddress }
     *     
     */
    public void setPAYERADDR(PayerAddress value) {
        this.payeraddr = value;
    }

    /**
     * Gets the value of the payerid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYERID() {
        return payerid;
    }

    /**
     * Sets the value of the payerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYERID(String value) {
        this.payerid = value;
    }

    /**
     * Gets the value of the recaddr property.
     * 
     * @return
     *     possible object is
     *     {@link RecurringAddress }
     *     
     */
    public RecurringAddress getRECADDR() {
        return recaddr;
    }

    /**
     * Sets the value of the recaddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecurringAddress }
     *     
     */
    public void setRECADDR(RecurringAddress value) {
        this.recaddr = value;
    }

    /**
     * Gets the value of the recid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECID() {
        return recid;
    }

    /**
     * Sets the value of the recid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECID(String value) {
        this.recid = value;
    }

    /**
     * Gets the value of the recacct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECACCT() {
        return recacct;
    }

    /**
     * Sets the value of the recacct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECACCT(String value) {
        this.recacct = value;
    }

    /**
     * Gets the value of the tinnot property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getTINNOT() {
        return tinnot;
    }

    /**
     * Sets the value of the tinnot property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setTINNOT(BooleanType value) {
        this.tinnot = value;
    }

}
