//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "TAX1098MSGSRQV1" is of type "Tax1098RequestMessageSetV1"
 *       
 * 
 * <p>Java class for Tax1098RequestMessageSetV1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tax1098RequestMessageSetV1">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractRequestMessageSet">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="TAX1098TRNRQ" type="{http://ofx.net/types/2003/04}Tax1098TransactionRequest"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tax1098RequestMessageSetV1", propOrder = {
    "tax1098TRNRQ"
})
public class Tax1098RequestMessageSetV1
    extends AbstractRequestMessageSet
{

    @XmlElement(name = "TAX1098TRNRQ", required = true)
    protected List<Tax1098TransactionRequest> tax1098TRNRQ;

    /**
     * Gets the value of the tax1098TRNRQ property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tax1098TRNRQ property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTAX1098TRNRQ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tax1098TransactionRequest }
     * 
     * 
     */
    public List<Tax1098TransactionRequest> getTAX1098TRNRQ() {
        if (tax1098TRNRQ == null) {
            tax1098TRNRQ = new ArrayList<Tax1098TransactionRequest>();
        }
        return this.tax1098TRNRQ;
    }

}
