//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "TAX1098MSGSET" is of type "Tax1098MessageSet"
 *       
 * 
 * <p>Java class for Tax1098MessageSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tax1098MessageSet">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractMessageSet">
 *       &lt;sequence>
 *         &lt;element name="TAX1098MSGSETV1" type="{http://ofx.net/types/2003/04}Tax1098MessageSetV1"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tax1098MessageSet", propOrder = {
    "tax1098MSGSETV1"
})
public class Tax1098MessageSet
    extends AbstractMessageSet
{

    @XmlElement(name = "TAX1098MSGSETV1", required = true)
    protected Tax1098MessageSetV1 tax1098MSGSETV1;

    /**
     * Gets the value of the tax1098MSGSETV1 property.
     * 
     * @return
     *     possible object is
     *     {@link Tax1098MessageSetV1 }
     *     
     */
    public Tax1098MessageSetV1 getTAX1098MSGSETV1() {
        return tax1098MSGSETV1;
    }

    /**
     * Sets the value of the tax1098MSGSETV1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tax1098MessageSetV1 }
     *     
     */
    public void setTAX1098MSGSETV1(Tax1098MessageSetV1 value) {
        this.tax1098MSGSETV1 = value;
    }

}
