//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "TAX1099TRNRQ" is of type "Tax1099TransactionRequest"
 *       
 * 
 * <p>Java class for Tax1099TransactionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tax1099TransactionRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TRNUID" type="{http://ofx.net/types/2003/04}GloballyUniqueUserIdType"/>
 *         &lt;element name="CLTCOOKIE" type="{http://ofx.net/types/2003/04}IdType" minOccurs="0"/>
 *         &lt;element name="TAN" type="{http://ofx.net/types/2003/04}TransactionAuthorizationNumberType" minOccurs="0"/>
 *         &lt;element name="TAX1099RQ" type="{http://ofx.net/types/2003/04}Tax1099Request"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tax1099TransactionRequest", propOrder = {
    "trnuid",
    "cltcookie",
    "tan",
    "tax1099RQ"
})
public class Tax1099TransactionRequest {

    @XmlElement(name = "TRNUID", required = true)
    protected String trnuid;
    @XmlElement(name = "CLTCOOKIE")
    protected String cltcookie;
    @XmlElement(name = "TAN")
    protected String tan;
    @XmlElement(name = "TAX1099RQ", required = true)
    protected Tax1099Request tax1099RQ;

    /**
     * Gets the value of the trnuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRNUID() {
        return trnuid;
    }

    /**
     * Sets the value of the trnuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRNUID(String value) {
        this.trnuid = value;
    }

    /**
     * Gets the value of the cltcookie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLTCOOKIE() {
        return cltcookie;
    }

    /**
     * Sets the value of the cltcookie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLTCOOKIE(String value) {
        this.cltcookie = value;
    }

    /**
     * Gets the value of the tan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAN() {
        return tan;
    }

    /**
     * Sets the value of the tan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAN(String value) {
        this.tan = value;
    }

    /**
     * Gets the value of the tax1099RQ property.
     * 
     * @return
     *     possible object is
     *     {@link Tax1099Request }
     *     
     */
    public Tax1099Request getTAX1099RQ() {
        return tax1099RQ;
    }

    /**
     * Sets the value of the tax1099RQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tax1099Request }
     *     
     */
    public void setTAX1099RQ(Tax1099Request value) {
        this.tax1099RQ = value;
    }

}
