//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "TAX1099R_V100" is of type "Tax1099R_V100"
 *       
 * 
 * <p>Java class for Tax1099R_V100 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tax1099R_V100">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractTaxForm1099">
 *       &lt;sequence>
 *         &lt;element name="GROSSDIST" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="TAXAMT" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="TAXAMTND" type="{http://ofx.net/types/2003/04}BooleanType" minOccurs="0"/>
 *         &lt;element name="TOTALDIST" type="{http://ofx.net/types/2003/04}BooleanType" minOccurs="0"/>
 *         &lt;element name="CAPGAIN" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="FEDTAXWH" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="EMPCONTINS" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="NETUNAPEMP" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="DISTCODE" type="{http://ofx.net/types/2003/04}CharType" maxOccurs="unbounded"/>
 *         &lt;element name="IRASEPSIMP" type="{http://ofx.net/types/2003/04}BooleanType" minOccurs="0"/>
 *         &lt;element name="ANNCTRCTDIST" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="ANNCTRCTPER" type="{http://ofx.net/types/2003/04}RateType" minOccurs="0"/>
 *         &lt;element name="PERTOTDIST" type="{http://ofx.net/types/2003/04}RateType" minOccurs="0"/>
 *         &lt;element name="TOTEMPCONT" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="STTAXWHAGG" type="{http://ofx.net/types/2003/04}StateTaxWithheldAggregate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LCLTAXWHAGG" type="{http://ofx.net/types/2003/04}LocalTaxWithheldAggregate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PAYERADDR" type="{http://ofx.net/types/2003/04}PayerAddress"/>
 *         &lt;element name="PAYERID" type="{http://ofx.net/types/2003/04}GenericNameType"/>
 *         &lt;element name="RECADDR" type="{http://ofx.net/types/2003/04}RecurringAddress" minOccurs="0"/>
 *         &lt;element name="RECID" type="{http://ofx.net/types/2003/04}IdType"/>
 *         &lt;element name="RECACCT" type="{http://ofx.net/types/2003/04}GenericNameType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tax1099R_V100", propOrder = {
    "grossdist",
    "taxamt",
    "taxamtnd",
    "totaldist",
    "capgain",
    "fedtaxwh",
    "empcontins",
    "netunapemp",
    "distcode",
    "irasepsimp",
    "annctrctdist",
    "annctrctper",
    "pertotdist",
    "totempcont",
    "sttaxwhagg",
    "lcltaxwhagg",
    "payeraddr",
    "payerid",
    "recaddr",
    "recid",
    "recacct"
})
public class Tax1099RV100
    extends AbstractTaxForm1099
{

    @XmlElement(name = "GROSSDIST")
    protected String grossdist;
    @XmlElement(name = "TAXAMT")
    protected String taxamt;
    @XmlElement(name = "TAXAMTND")
    protected BooleanType taxamtnd;
    @XmlElement(name = "TOTALDIST")
    protected BooleanType totaldist;
    @XmlElement(name = "CAPGAIN")
    protected String capgain;
    @XmlElement(name = "FEDTAXWH")
    protected String fedtaxwh;
    @XmlElement(name = "EMPCONTINS")
    protected String empcontins;
    @XmlElement(name = "NETUNAPEMP")
    protected String netunapemp;
    @XmlElement(name = "DISTCODE", required = true)
    protected List<String> distcode;
    @XmlElement(name = "IRASEPSIMP")
    protected BooleanType irasepsimp;
    @XmlElement(name = "ANNCTRCTDIST")
    protected String annctrctdist;
    @XmlElement(name = "ANNCTRCTPER")
    protected String annctrctper;
    @XmlElement(name = "PERTOTDIST")
    protected String pertotdist;
    @XmlElement(name = "TOTEMPCONT")
    protected String totempcont;
    @XmlElement(name = "STTAXWHAGG")
    protected List<StateTaxWithheldAggregate> sttaxwhagg;
    @XmlElement(name = "LCLTAXWHAGG")
    protected List<LocalTaxWithheldAggregate> lcltaxwhagg;
    @XmlElement(name = "PAYERADDR", required = true)
    protected PayerAddress payeraddr;
    @XmlElement(name = "PAYERID", required = true)
    protected String payerid;
    @XmlElement(name = "RECADDR")
    protected RecurringAddress recaddr;
    @XmlElement(name = "RECID", required = true)
    protected String recid;
    @XmlElement(name = "RECACCT")
    protected String recacct;

    /**
     * Gets the value of the grossdist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGROSSDIST() {
        return grossdist;
    }

    /**
     * Sets the value of the grossdist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGROSSDIST(String value) {
        this.grossdist = value;
    }

    /**
     * Gets the value of the taxamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXAMT() {
        return taxamt;
    }

    /**
     * Sets the value of the taxamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXAMT(String value) {
        this.taxamt = value;
    }

    /**
     * Gets the value of the taxamtnd property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getTAXAMTND() {
        return taxamtnd;
    }

    /**
     * Sets the value of the taxamtnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setTAXAMTND(BooleanType value) {
        this.taxamtnd = value;
    }

    /**
     * Gets the value of the totaldist property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getTOTALDIST() {
        return totaldist;
    }

    /**
     * Sets the value of the totaldist property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setTOTALDIST(BooleanType value) {
        this.totaldist = value;
    }

    /**
     * Gets the value of the capgain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAPGAIN() {
        return capgain;
    }

    /**
     * Sets the value of the capgain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAPGAIN(String value) {
        this.capgain = value;
    }

    /**
     * Gets the value of the fedtaxwh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFEDTAXWH() {
        return fedtaxwh;
    }

    /**
     * Sets the value of the fedtaxwh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFEDTAXWH(String value) {
        this.fedtaxwh = value;
    }

    /**
     * Gets the value of the empcontins property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMPCONTINS() {
        return empcontins;
    }

    /**
     * Sets the value of the empcontins property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMPCONTINS(String value) {
        this.empcontins = value;
    }

    /**
     * Gets the value of the netunapemp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNETUNAPEMP() {
        return netunapemp;
    }

    /**
     * Sets the value of the netunapemp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNETUNAPEMP(String value) {
        this.netunapemp = value;
    }

    /**
     * Gets the value of the distcode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the distcode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDISTCODE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDISTCODE() {
        if (distcode == null) {
            distcode = new ArrayList<String>();
        }
        return this.distcode;
    }

    /**
     * Gets the value of the irasepsimp property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getIRASEPSIMP() {
        return irasepsimp;
    }

    /**
     * Sets the value of the irasepsimp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setIRASEPSIMP(BooleanType value) {
        this.irasepsimp = value;
    }

    /**
     * Gets the value of the annctrctdist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANNCTRCTDIST() {
        return annctrctdist;
    }

    /**
     * Sets the value of the annctrctdist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANNCTRCTDIST(String value) {
        this.annctrctdist = value;
    }

    /**
     * Gets the value of the annctrctper property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANNCTRCTPER() {
        return annctrctper;
    }

    /**
     * Sets the value of the annctrctper property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANNCTRCTPER(String value) {
        this.annctrctper = value;
    }

    /**
     * Gets the value of the pertotdist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPERTOTDIST() {
        return pertotdist;
    }

    /**
     * Sets the value of the pertotdist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPERTOTDIST(String value) {
        this.pertotdist = value;
    }

    /**
     * Gets the value of the totempcont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTEMPCONT() {
        return totempcont;
    }

    /**
     * Sets the value of the totempcont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTEMPCONT(String value) {
        this.totempcont = value;
    }

    /**
     * Gets the value of the sttaxwhagg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sttaxwhagg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTTAXWHAGG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StateTaxWithheldAggregate }
     * 
     * 
     */
    public List<StateTaxWithheldAggregate> getSTTAXWHAGG() {
        if (sttaxwhagg == null) {
            sttaxwhagg = new ArrayList<StateTaxWithheldAggregate>();
        }
        return this.sttaxwhagg;
    }

    /**
     * Gets the value of the lcltaxwhagg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lcltaxwhagg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLCLTAXWHAGG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalTaxWithheldAggregate }
     * 
     * 
     */
    public List<LocalTaxWithheldAggregate> getLCLTAXWHAGG() {
        if (lcltaxwhagg == null) {
            lcltaxwhagg = new ArrayList<LocalTaxWithheldAggregate>();
        }
        return this.lcltaxwhagg;
    }

    /**
     * Gets the value of the payeraddr property.
     * 
     * @return
     *     possible object is
     *     {@link PayerAddress }
     *     
     */
    public PayerAddress getPAYERADDR() {
        return payeraddr;
    }

    /**
     * Sets the value of the payeraddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerAddress }
     *     
     */
    public void setPAYERADDR(PayerAddress value) {
        this.payeraddr = value;
    }

    /**
     * Gets the value of the payerid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYERID() {
        return payerid;
    }

    /**
     * Sets the value of the payerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYERID(String value) {
        this.payerid = value;
    }

    /**
     * Gets the value of the recaddr property.
     * 
     * @return
     *     possible object is
     *     {@link RecurringAddress }
     *     
     */
    public RecurringAddress getRECADDR() {
        return recaddr;
    }

    /**
     * Sets the value of the recaddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecurringAddress }
     *     
     */
    public void setRECADDR(RecurringAddress value) {
        this.recaddr = value;
    }

    /**
     * Gets the value of the recid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECID() {
        return recid;
    }

    /**
     * Sets the value of the recid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECID(String value) {
        this.recid = value;
    }

    /**
     * Gets the value of the recacct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECACCT() {
        return recacct;
    }

    /**
     * Sets the value of the recacct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECACCT(String value) {
        this.recacct = value;
    }

}
