//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "TAX1099MSGSRQV1" is of type "Tax1099RequestMessageSetV1"
 *       
 * 
 * <p>Java class for Tax1099RequestMessageSetV1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tax1099RequestMessageSetV1">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractRequestMessageSet">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="TAX1099TRNRQ" type="{http://ofx.net/types/2003/04}Tax1099TransactionRequest"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tax1099RequestMessageSetV1", propOrder = {
    "tax1099TRNRQ"
})
public class Tax1099RequestMessageSetV1
    extends AbstractRequestMessageSet
{

    @XmlElement(name = "TAX1099TRNRQ", required = true)
    protected List<Tax1099TransactionRequest> tax1099TRNRQ;

    /**
     * Gets the value of the tax1099TRNRQ property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tax1099TRNRQ property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTAX1099TRNRQ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tax1099TransactionRequest }
     * 
     * 
     */
    public List<Tax1099TransactionRequest> getTAX1099TRNRQ() {
        if (tax1099TRNRQ == null) {
            tax1099TRNRQ = new ArrayList<Tax1099TransactionRequest>();
        }
        return this.tax1099TRNRQ;
    }

}
