//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "TAXW2TRNRQ" is of type "TaxW2TransactionRequest"
 *       
 * 
 * <p>Java class for TaxW2TransactionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxW2TransactionRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TRNUID" type="{http://ofx.net/types/2003/04}GloballyUniqueUserIdType"/>
 *         &lt;element name="CLTCOOKIE" type="{http://ofx.net/types/2003/04}IdType" minOccurs="0"/>
 *         &lt;element name="TAN" type="{http://ofx.net/types/2003/04}TransactionAuthorizationNumberType" minOccurs="0"/>
 *         &lt;element name="TAXW2RQ" type="{http://ofx.net/types/2003/04}TaxW2Request"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxW2TransactionRequest", propOrder = {
    "trnuid",
    "cltcookie",
    "tan",
    "taxw2RQ"
})
public class TaxW2TransactionRequest {

    @XmlElement(name = "TRNUID", required = true)
    protected String trnuid;
    @XmlElement(name = "CLTCOOKIE")
    protected String cltcookie;
    @XmlElement(name = "TAN")
    protected String tan;
    @XmlElement(name = "TAXW2RQ", required = true)
    protected TaxW2Request taxw2RQ;

    /**
     * Gets the value of the trnuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRNUID() {
        return trnuid;
    }

    /**
     * Sets the value of the trnuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRNUID(String value) {
        this.trnuid = value;
    }

    /**
     * Gets the value of the cltcookie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLTCOOKIE() {
        return cltcookie;
    }

    /**
     * Sets the value of the cltcookie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLTCOOKIE(String value) {
        this.cltcookie = value;
    }

    /**
     * Gets the value of the tan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAN() {
        return tan;
    }

    /**
     * Sets the value of the tan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAN(String value) {
        this.tan = value;
    }

    /**
     * Gets the value of the taxw2RQ property.
     * 
     * @return
     *     possible object is
     *     {@link TaxW2Request }
     *     
     */
    public TaxW2Request getTAXW2RQ() {
        return taxw2RQ;
    }

    /**
     * Sets the value of the taxw2RQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxW2Request }
     *     
     */
    public void setTAXW2RQ(TaxW2Request value) {
        this.taxw2RQ = value;
    }

}
