//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "TAXW2MSGSRQV1" is of type "TaxW2RequestMessageSetV1"
 *       
 * 
 * <p>Java class for TaxW2RequestMessageSetV1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxW2RequestMessageSetV1">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractRequestMessageSet">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="TAXW2TRNRQ" type="{http://ofx.net/types/2003/04}TaxW2TransactionRequest"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxW2RequestMessageSetV1", propOrder = {
    "taxw2TRNRQ"
})
public class TaxW2RequestMessageSetV1
    extends AbstractRequestMessageSet
{

    @XmlElement(name = "TAXW2TRNRQ", required = true)
    protected List<TaxW2TransactionRequest> taxw2TRNRQ;

    /**
     * Gets the value of the taxw2TRNRQ property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxw2TRNRQ property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTAXW2TRNRQ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxW2TransactionRequest }
     * 
     * 
     */
    public List<TaxW2TransactionRequest> getTAXW2TRNRQ() {
        if (taxw2TRNRQ == null) {
            taxw2TRNRQ = new ArrayList<TaxW2TransactionRequest>();
        }
        return this.taxw2TRNRQ;
    }

}
