//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "TRANSFER" is of type "Transfer"
 *       
 * 
 * <p>Java class for Transfer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Transfer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractInvestmentTransaction">
 *       &lt;sequence>
 *         &lt;element name="SECID" type="{http://ofx.net/types/2003/04}SecurityId"/>
 *         &lt;element name="SUBACCTSEC" type="{http://ofx.net/types/2003/04}SubAccountEnum"/>
 *         &lt;element name="UNITS" type="{http://ofx.net/types/2003/04}QuantityType"/>
 *         &lt;element name="TFERACTION" type="{http://ofx.net/types/2003/04}InOutEnum"/>
 *         &lt;element name="POSTYPE" type="{http://ofx.net/types/2003/04}PositionTypeEnum"/>
 *         &lt;element name="INVACCTFROM" type="{http://ofx.net/types/2003/04}InvestmentAccount" minOccurs="0"/>
 *         &lt;element name="AVGCOSTBASIS" type="{http://ofx.net/types/2003/04}AmountType" minOccurs="0"/>
 *         &lt;element name="UNITPRICE" type="{http://ofx.net/types/2003/04}UnitPriceType" minOccurs="0"/>
 *         &lt;element name="DTPURCHASE" type="{http://ofx.net/types/2003/04}DateTimeType" minOccurs="0"/>
 *         &lt;element name="INV401KSOURCE" type="{http://ofx.net/types/2003/04}Investment401kSourceEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Transfer", propOrder = {
    "secid",
    "subacctsec",
    "units",
    "tferaction",
    "postype",
    "invacctfrom",
    "avgcostbasis",
    "unitprice",
    "dtpurchase",
    "inv401KSOURCE"
})
public class Transfer
    extends AbstractInvestmentTransaction
{

    @XmlElement(name = "SECID", required = true)
    protected SecurityId secid;
    @XmlElement(name = "SUBACCTSEC", required = true)
    protected SubAccountEnum subacctsec;
    @XmlElement(name = "UNITS", required = true)
    protected String units;
    @XmlElement(name = "TFERACTION", required = true)
    protected InOutEnum tferaction;
    @XmlElement(name = "POSTYPE", required = true)
    protected PositionTypeEnum postype;
    @XmlElement(name = "INVACCTFROM")
    protected InvestmentAccount invacctfrom;
    @XmlElement(name = "AVGCOSTBASIS")
    protected String avgcostbasis;
    @XmlElement(name = "UNITPRICE")
    protected String unitprice;
    @XmlElement(name = "DTPURCHASE")
    protected String dtpurchase;
    @XmlElement(name = "INV401KSOURCE")
    protected Investment401KSourceEnum inv401KSOURCE;

    /**
     * Gets the value of the secid property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityId }
     *     
     */
    public SecurityId getSECID() {
        return secid;
    }

    /**
     * Sets the value of the secid property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityId }
     *     
     */
    public void setSECID(SecurityId value) {
        this.secid = value;
    }

    /**
     * Gets the value of the subacctsec property.
     * 
     * @return
     *     possible object is
     *     {@link SubAccountEnum }
     *     
     */
    public SubAccountEnum getSUBACCTSEC() {
        return subacctsec;
    }

    /**
     * Sets the value of the subacctsec property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubAccountEnum }
     *     
     */
    public void setSUBACCTSEC(SubAccountEnum value) {
        this.subacctsec = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNITS() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNITS(String value) {
        this.units = value;
    }

    /**
     * Gets the value of the tferaction property.
     * 
     * @return
     *     possible object is
     *     {@link InOutEnum }
     *     
     */
    public InOutEnum getTFERACTION() {
        return tferaction;
    }

    /**
     * Sets the value of the tferaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link InOutEnum }
     *     
     */
    public void setTFERACTION(InOutEnum value) {
        this.tferaction = value;
    }

    /**
     * Gets the value of the postype property.
     * 
     * @return
     *     possible object is
     *     {@link PositionTypeEnum }
     *     
     */
    public PositionTypeEnum getPOSTYPE() {
        return postype;
    }

    /**
     * Sets the value of the postype property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionTypeEnum }
     *     
     */
    public void setPOSTYPE(PositionTypeEnum value) {
        this.postype = value;
    }

    /**
     * Gets the value of the invacctfrom property.
     * 
     * @return
     *     possible object is
     *     {@link InvestmentAccount }
     *     
     */
    public InvestmentAccount getINVACCTFROM() {
        return invacctfrom;
    }

    /**
     * Sets the value of the invacctfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvestmentAccount }
     *     
     */
    public void setINVACCTFROM(InvestmentAccount value) {
        this.invacctfrom = value;
    }

    /**
     * Gets the value of the avgcostbasis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVGCOSTBASIS() {
        return avgcostbasis;
    }

    /**
     * Sets the value of the avgcostbasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVGCOSTBASIS(String value) {
        this.avgcostbasis = value;
    }

    /**
     * Gets the value of the unitprice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNITPRICE() {
        return unitprice;
    }

    /**
     * Sets the value of the unitprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNITPRICE(String value) {
        this.unitprice = value;
    }

    /**
     * Gets the value of the dtpurchase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTPURCHASE() {
        return dtpurchase;
    }

    /**
     * Sets the value of the dtpurchase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTPURCHASE(String value) {
        this.dtpurchase = value;
    }

    /**
     * Gets the value of the inv401KSOURCE property.
     * 
     * @return
     *     possible object is
     *     {@link Investment401KSourceEnum }
     *     
     */
    public Investment401KSourceEnum getINV401KSOURCE() {
        return inv401KSOURCE;
    }

    /**
     * Sets the value of the inv401KSOURCE property.
     * 
     * @param value
     *     allowed object is
     *     {@link Investment401KSourceEnum }
     *     
     */
    public void setINV401KSOURCE(Investment401KSourceEnum value) {
        this.inv401KSOURCE = value;
    }

}
