//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "XFERINFO" is of type "TransferInfo"
 *       
 * 
 * <p>Java class for TransferInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransferInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="BANKACCTFROM" type="{http://ofx.net/types/2003/04}BankAccount"/>
 *           &lt;element name="CCACCTFROM" type="{http://ofx.net/types/2003/04}CreditCardAccount"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="BANKACCTTO" type="{http://ofx.net/types/2003/04}BankAccount"/>
 *           &lt;element name="CCACCTTO" type="{http://ofx.net/types/2003/04}CreditCardAccount"/>
 *         &lt;/choice>
 *         &lt;element name="TRNAMT" type="{http://ofx.net/types/2003/04}AmountType"/>
 *         &lt;element name="DTDUE" type="{http://ofx.net/types/2003/04}DateTimeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransferInfo", propOrder = {
    "bankacctfrom",
    "ccacctfrom",
    "bankacctto",
    "ccacctto",
    "trnamt",
    "dtdue"
})
public class TransferInfo {

    @XmlElement(name = "BANKACCTFROM")
    protected BankAccount bankacctfrom;
    @XmlElement(name = "CCACCTFROM")
    protected CreditCardAccount ccacctfrom;
    @XmlElement(name = "BANKACCTTO")
    protected BankAccount bankacctto;
    @XmlElement(name = "CCACCTTO")
    protected CreditCardAccount ccacctto;
    @XmlElement(name = "TRNAMT", required = true)
    protected String trnamt;
    @XmlElement(name = "DTDUE")
    protected String dtdue;

    /**
     * Gets the value of the bankacctfrom property.
     * 
     * @return
     *     possible object is
     *     {@link BankAccount }
     *     
     */
    public BankAccount getBANKACCTFROM() {
        return bankacctfrom;
    }

    /**
     * Sets the value of the bankacctfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankAccount }
     *     
     */
    public void setBANKACCTFROM(BankAccount value) {
        this.bankacctfrom = value;
    }

    /**
     * Gets the value of the ccacctfrom property.
     * 
     * @return
     *     possible object is
     *     {@link CreditCardAccount }
     *     
     */
    public CreditCardAccount getCCACCTFROM() {
        return ccacctfrom;
    }

    /**
     * Sets the value of the ccacctfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditCardAccount }
     *     
     */
    public void setCCACCTFROM(CreditCardAccount value) {
        this.ccacctfrom = value;
    }

    /**
     * Gets the value of the bankacctto property.
     * 
     * @return
     *     possible object is
     *     {@link BankAccount }
     *     
     */
    public BankAccount getBANKACCTTO() {
        return bankacctto;
    }

    /**
     * Sets the value of the bankacctto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankAccount }
     *     
     */
    public void setBANKACCTTO(BankAccount value) {
        this.bankacctto = value;
    }

    /**
     * Gets the value of the ccacctto property.
     * 
     * @return
     *     possible object is
     *     {@link CreditCardAccount }
     *     
     */
    public CreditCardAccount getCCACCTTO() {
        return ccacctto;
    }

    /**
     * Sets the value of the ccacctto property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditCardAccount }
     *     
     */
    public void setCCACCTTO(CreditCardAccount value) {
        this.ccacctto = value;
    }

    /**
     * Gets the value of the trnamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRNAMT() {
        return trnamt;
    }

    /**
     * Sets the value of the trnamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRNAMT(String value) {
        this.trnamt = value;
    }

    /**
     * Gets the value of the dtdue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTDUE() {
        return dtdue;
    }

    /**
     * Sets the value of the dtdue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTDUE(String value) {
        this.dtdue = value;
    }

}
