//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 	      The OFX element "VESTINFO" is of type "VestInfo"
 * 	    
 * 
 * <p>Java class for VestInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VestInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VESTDATE" type="{http://ofx.net/types/2003/04}DateTimeType" minOccurs="0"/>
 *         &lt;element name="VESTPCT" type="{http://ofx.net/types/2003/04}RateType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VestInfo", propOrder = {
    "vestdate",
    "vestpct"
})
public class VestInfo {

    @XmlElement(name = "VESTDATE")
    protected String vestdate;
    @XmlElement(name = "VESTPCT", required = true)
    protected String vestpct;

    /**
     * Gets the value of the vestdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVESTDATE() {
        return vestdate;
    }

    /**
     * Sets the value of the vestdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVESTDATE(String value) {
        this.vestdate = value;
    }

    /**
     * Gets the value of the vestpct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVESTPCT() {
        return vestpct;
    }

    /**
     * Sets the value of the vestpct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVESTPCT(String value) {
        this.vestpct = value;
    }

}
