//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 04:58:05 PM EST 
//


package ofx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The OFX element "WIRETRNRQ" is of type "WireTransactionRequest"
 *       
 * 
 * <p>Java class for WireTransactionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WireTransactionRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ofx.net/types/2003/04}AbstractTransactionRequest">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="WIRERQ" type="{http://ofx.net/types/2003/04}WireRequest"/>
 *           &lt;element name="WIRECANRQ" type="{http://ofx.net/types/2003/04}WireCancellationRequest"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WireTransactionRequest", propOrder = {
    "wirerq",
    "wirecanrq"
})
public class WireTransactionRequest
    extends AbstractTransactionRequest
{

    @XmlElement(name = "WIRERQ")
    protected WireRequest wirerq;
    @XmlElement(name = "WIRECANRQ")
    protected WireCancellationRequest wirecanrq;

    /**
     * Gets the value of the wirerq property.
     * 
     * @return
     *     possible object is
     *     {@link WireRequest }
     *     
     */
    public WireRequest getWIRERQ() {
        return wirerq;
    }

    /**
     * Sets the value of the wirerq property.
     * 
     * @param value
     *     allowed object is
     *     {@link WireRequest }
     *     
     */
    public void setWIRERQ(WireRequest value) {
        this.wirerq = value;
    }

    /**
     * Gets the value of the wirecanrq property.
     * 
     * @return
     *     possible object is
     *     {@link WireCancellationRequest }
     *     
     */
    public WireCancellationRequest getWIRECANRQ() {
        return wirecanrq;
    }

    /**
     * Sets the value of the wirecanrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link WireCancellationRequest }
     *     
     */
    public void setWIRECANRQ(WireCancellationRequest value) {
        this.wirecanrq = value;
    }

}
